import '../config/config.dart';
import '../models/project_model.dart';
import '../models/variable_type.dart';
import '../utils/locale.dart';

/// Generate a TypeScript ambient declaration for `NodeJS.ProcessEnv`.
/// Values are never emitted — only names, plus inferred type / secret
/// hints as JSDoc.
String generateEnvTypes(ProjectModel model, EnvdoctorConfig config) {
  final names = <String, ({bool isSecret, String? inferredType})>{};

  for (final file in model.allFiles) {
    for (final v in file.variables) {
      final existing = names[v.name];
      if (existing == null) {
        names[v.name] = (
          isSecret: v.isSecret,
          inferredType: v.type == VariableType.unknown ? null : v.type.str,
        );
      } else if (v.type != VariableType.unknown && existing.inferredType == null) {
        names[v.name] = (isSecret: existing.isSecret, inferredType: v.type.str);
      }
    }
    for (final v in file.usages) {
      names.putIfAbsent(v.name, () => (isSecret: v.isSecret, inferredType: null));
    }
  }

  final lines = <String>[
    '// Generated by envdoctor. Do not edit manually.',
    '// This file declares types for process.env variables.',
    '// Secret values are never included.',
    '',
    'declare global {',
    '  namespace NodeJS {',
    '    interface ProcessEnv {',
  ];

  final sortedNames = names.keys.toList();
  localeSort(sortedNames);
  for (final name in sortedNames) {
    final meta = names[name]!;
    final docParts = <String>[];
    if (meta.isSecret) docParts.add('secret');
    final t = meta.inferredType;
    if (t != null) docParts.add('inferred type: $t');
    if (docParts.isNotEmpty) {
      lines.add('      /** ${docParts.join(' · ')} */');
    }
    lines.add('      $name: string;');
  }

  lines.add('    }');
  lines.add('  }');
  lines.add('}');
  lines.add('');
  lines.add('export {};');
  lines.add('');

  return lines.join('\n');
}
