import '../config/config.dart';
import '../models/environment_variable.dart';
import '../models/project_model.dart';
import '../utils/locale.dart';

/// Generate a deterministic `.env.example` for a project.
///
/// - Secret-like names always get a blank value.
/// - Non-secret values are copied ONLY from the base `.env` (development)
///   file; never from `.env.production`, `.env.local`, etc., and never a
///   secret value.
String generateEnvExample(ProjectModel model, EnvdoctorConfig config) {
  // Names the app actually consumes (source + compose + actions).
  final used = <String>{};
  for (final file in [...model.sourceFiles, ...model.composeFiles, ...model.actionFiles]) {
    for (final v in file.variables) {
      used.add(v.name);
    }
    for (final v in file.usages) {
      used.add(v.name);
    }
  }

  // Names defined in environment files (including `.env.example`).
  final defined = <String>{};
  for (final file in model.envFiles) {
    for (final v in file.variables) {
      defined.add(v.name);
    }
  }

  final required = used;
  final optional = defined.where((n) => !used.contains(n)).toList();

  final lines = <String>[
    '# .env.example',
    '# Generated by envdoctor. Copy to .env and fill in real values.',
    '# Secret values are intentionally left blank — never commit secrets.',
    '',
  ];

  if (required.isNotEmpty) {
    lines.add('# Required by the application');
    final names = required.toList();
    localeSort(names);
    for (final name in names) {
      lines.add('$name=${_valueFor(model, name)}');
    }
    lines.add('');
  }

  if (optional.isNotEmpty) {
    lines.add('# Optional / configuration knobs');
    final names = optional;
    localeSort(names);
    for (final name in names) {
      lines.add('$name=${_valueFor(model, name)}');
    }
    lines.add('');
  }

  return lines.join('\n');
}

/// The value written for a name: blank for secrets, else the non-empty
/// value from the development `.env`, else blank.
String _valueFor(ProjectModel model, String name) {
  if (EnvironmentVariable.isSecretName(name)) return '';
  for (final file in model.envFiles) {
    if (file.environment != 'development') continue;
    for (final v in file.variables) {
      if (v.name == name && (v.value ?? '').isNotEmpty) return v.value ?? '';
    }
  }
  return '';
}
