import '../config/config.dart';
import '../models/project_model.dart';
import '../models/variable_type.dart';
import '../utils/locale.dart';

/// Generates `ENVIRONMENT.md`. Names only — no values ever appear. Note the
/// reference sorts the overview / per-environment lists with `localeCompare`
/// but the "missing" list and environment labels with the default (code-unit)
/// sort; both are reproduced here.
String generateEnvironmentDoc(ProjectModel model, EnvdoctorConfig config) {
  final names = _collectNames(model);

  final lines = <String>[
    '# Environment Variables',
    '',
    '> Generated by envdoctor. Do not edit by hand — run `envdoctor fix` to regenerate.',
    '',
  ];

  // ---- Overview table ----
  lines.add('## Overview');
  lines.add('');
  lines.add('| Variable | Type | Defined in | Used in source | Secret |');
  lines.add('| --- | --- | --- | --- | --- |');
  for (final name in names.sorted) {
    final info = names.info[name];
    final ty = info?.type ?? 'unknown';
    final envs = info != null && info.environments.isNotEmpty
        ? info.environments.join(', ')
        : '—';
    final source = info?.usedInSource == true ? '✓' : '—';
    final secret = info?.isSecret == true ? '✓' : '—';
    lines.add('| $name | $ty | $envs | $source | $secret |');
  }
  lines.add('');

  // ---- Missing ----
  if (names.missing.isNotEmpty) {
    lines.add('## Referenced but not defined');
    lines.add('');
    lines.add(
        'These variables are expected somewhere in the project but are not defined in any environment file:');
    lines.add('');
    for (final name in names.missing) {
      lines.add('- `$name`');
    }
    lines.add('');
  }

  // ---- Per-environment sections ----
  lines.add('## Environments');
  lines.add('');
  final envLabels = _distinctEnvLabels(model);
  if (envLabels.isEmpty) {
    lines.add('No environment files found.');
    lines.add('');
  } else {
    for (final label in envLabels) {
      final files = model.envFiles
          .where((file) => file.environment == label)
          .map((file) => '`${file.filePath}`')
          .toList();
      lines.add('### $label');
      lines.add('');
      lines.add(files.isNotEmpty ? 'Defined in ${files.join(', ')}.' : '');
      for (final name in names.sorted) {
        final info = names.info[name];
        if (info != null &&
            info.environments.isNotEmpty &&
            info.environments.contains(label)) {
          lines.add('- $name');
        }
      }
      lines.add('');
    }
  }

  return lines.join('\n');
}

class _NameInfo {
  String? type;
  final List<String> environments = [];
  bool usedInSource = false;
  bool isSecret = false;
}

class _NamesIndex {
  final List<String> sorted;
  final Map<String, _NameInfo> info;
  final List<String> missing;
  _NamesIndex(this.sorted, this.info, this.missing);
}

_NamesIndex _collectNames(ProjectModel model) {
  final names = <String>{};
  final info = <String, _NameInfo>{};
  final exampleNames = <String>{};

  // Definitions from environment files. `.env.example` is documentation —
  // it does not count as a real environment.
  for (final file in model.envFiles) {
    for (final v in file.variables) {
      names.add(v.name);
      if (file.environment == 'example') {
        exampleNames.add(v.name);
        continue;
      }
      final entry = info.putIfAbsent(v.name, () => _NameInfo()..isSecret = v.isSecret);
      if (file.environment != null && !entry.environments.contains(file.environment)) {
        entry.environments.add(file.environment!);
      }
      if (entry.type == null && v.type != VariableType.unknown) {
        entry.type = v.type.str;
      }
      entry.isSecret = entry.isSecret || v.isSecret;
    }
  }

  // Source usages.
  final sourceUsed = <String>{};
  for (final file in model.sourceFiles) {
    for (final v in file.usages) {
      names.add(v.name);
      sourceUsed.add(v.name);
    }
  }

  // Compose definitions and usages (GitHub Actions is intentionally excluded).
  final composeRefs = <String>{};
  for (final file in model.composeFiles) {
    for (final v in file.variables) {
      names.add(v.name);
      composeRefs.add(v.name);
      final entry = info.putIfAbsent(v.name, () => _NameInfo()..isSecret = v.isSecret);
      entry.isSecret = entry.isSecret || v.isSecret;
    }
    for (final v in file.usages) {
      names.add(v.name);
      composeRefs.add(v.name);
    }
  }

  for (final name in sourceUsed) {
    final entry = info.putIfAbsent(name, _NameInfo.new);
    entry.usedInSource = true;
  }

  // Referenced but not defined in any real environment file.
  final missing = names.where((n) {
    final i = info[n];
    if (i != null && i.environments.isNotEmpty) return false;
    return sourceUsed.contains(n) || composeRefs.contains(n) || exampleNames.contains(n);
  }).toList();
  missing.sort(); // default (code-unit) order

  final sorted = names.toList();
  localeSort(sorted);

  return _NamesIndex(sorted, info, missing);
}

List<String> _distinctEnvLabels(ProjectModel model) {
  final labels = <String>{};
  for (final file in model.envFiles) {
    if (file.environment != null && file.environment != 'example') {
      labels.add(file.environment!);
    }
  }
  final result = labels.toList();
  result.sort(); // default (code-unit) order
  return result;
}
