import '../config/config.dart';
import '../models/environment_variable.dart';
import '../models/project_model.dart';
import '../utils/glob.dart';

class ActionsChecklist {
  /// Names referenced via `${{ secrets.X }}`.
  final List<String> secrets;

  /// Names referenced via `${{ vars.X }}`.
  final List<String> vars;

  ActionsChecklist(this.secrets, this.vars);
}

/// Collect the repository secrets and variables referenced by a project's
/// GitHub Actions workflows.
ActionsChecklist collectActionsChecklist(ProjectModel model) {
  final secrets = <String>{};
  final vars = <String>{};

  for (final file in model.actionFiles) {
    for (final usage in file.usages) {
      for (final origin in usage.origins) {
        switch (origin.subkind) {
          case 'vars':
            vars.add(usage.name);
          case 'secrets':
            secrets.add(usage.name);
        }
      }
    }
  }

  final secretList = secrets.toList()..sort();
  final varList = vars.toList()..sort();
  return ActionsChecklist(secretList, varList);
}

/// Generate `.github/ENVIRONMENT.md` — a checklist of the repository
/// secrets and variables that must be configured for the workflows to
/// work. Names only; values are never mentioned.
String generateActionsChecklist(ProjectModel model) {
  final checklist = collectActionsChecklist(model);

  final lines = <String>[
    '# GitHub Actions environment checklist',
    '',
    '> Generated by envdoctor. Do not edit by hand.',
    '',
    'Configure these repository secrets and variables (Settings → Secrets and variables → Actions).',
    '',
  ];

  lines.add('## Secrets');
  if (checklist.secrets.isEmpty) {
    lines.add('None.');
  } else {
    for (final name in checklist.secrets) {
      lines.add('- [ ] `$name`');
    }
  }
  lines.add('');

  lines.add('## Variables');
  if (checklist.vars.isEmpty) {
    lines.add('None.');
  } else {
    for (final name in checklist.vars) {
      lines.add('- [ ] `$name`');
    }
  }
  lines.add('');

  return lines.join('\n');
}

/// Generate a GitHub Actions workflow snippet with env vars from the model.
String generateGithubActions(ProjectModel model, EnvdoctorConfig config) {
  final byName = <String, EnvironmentVariable>{};

  // Prefer env file definitions, then compose, then actions, then k8s.
  for (final files in [
    model.envFiles,
    model.composeFiles,
    model.actionFiles,
    model.k8sFiles,
  ]) {
    for (final file in files) {
      for (final v in file.variables) {
        if (config.ignoreVariables.isNotEmpty &&
            matchesAnyGlob(config.ignoreVariables, v.name)) {
          continue;
        }
        byName.putIfAbsent(v.name, () => v);
      }
    }
  }

  final names = byName.keys.toList()..sort();

  final out = StringBuffer();
  out.write('# Generated by envdoctor — add to your workflow.\n');
  out.write('# Replace \${{ secrets.X }} with your actual secret names.\n\n');

  // Separate secrets from regular vars.
  final secrets = <String>[];
  final regular = <String>[];

  for (final name in names) {
    if (byName[name]!.isSecret) {
      secrets.add(name);
    } else {
      regular.add(name);
    }
  }

  if (regular.isEmpty && secrets.isEmpty) return out.toString();

  out.write('env:\n');
  for (final name in regular) {
    final val = byName[name]!.value ?? 'REPLACE_ME';
    // Escape for YAML.
    final escaped = val.replaceAll('"', '\\"');
    out.write('  $name: "$escaped"\n');
  }
  for (final name in secrets) {
    out.write('  $name: \${{ secrets.${name.toUpperCase()} }}\n');
  }
  out.write('\n');

  return out.toString();
}
