import 'dart:io';

import '../models/project_model.dart';
import '../models/variable_type.dart';
import '../utils/json.dart';
import '../utils/locale.dart';
import '../utils/type_infer.dart' as type_infer;

/// Infer a validation schema for every known environment variable by
/// inspecting existing env values and source-code usage patterns, then
/// emit it as a TypeScript module (`envdoctor.schema.ts`).
String generateVariableSchemaTs(ProjectModel model) {
  // name → type string (e.g. "integer")
  final schema = <String, String>{};

  // Infer from existing env values first.
  for (final file in model.envFiles) {
    for (final v in file.variables) {
      if (v.value == null) continue;
      final mapped = _mapInferredType(type_infer.inferType(v.value));
      if (mapped != null) schema[v.name] = mapped;
    }
  }

  // Refine from source usage patterns.
  for (final file in model.sourceFiles) {
    final String content;
    try {
      content = File(file.filePath).readAsStringSync();
    } catch (_) {
      continue;
    }
    final lines = content.split('\n');
    for (final usage in file.usages) {
      for (final origin in usage.origins) {
        final lineNo = origin.line;
        if (lineNo == null) continue;
        final line = lineNo - 1 >= 0 && lineNo - 1 < lines.length ? lines[lineNo - 1] : '';
        final inferred = _inferFromLine(usage.name, line);
        if (inferred != null) schema[usage.name] = inferred;
      }
    }
  }

  if (schema.isEmpty) {
    return '// Generated by envdoctor. No schema could be inferred.\nexport default {\n  schema: {},\n};\n';
  }

  final linesOut = <String>[
    '// Generated by envdoctor. Merge into envdoctor.config.ts:',
    "// import schema from './envdoctor.schema'; export default { ..., ...schema };",
    '',
    'export default {',
    '  schema: {',
  ];
  // Match the TS reference: entries are ordered by `localeCompare`.
  final entries = schema.entries.toList()
    ..sort((a, b) => localeCompare(a.key, b.key));
  for (final entry in entries) {
    linesOut.add('    ${entry.key}: { type: "${entry.value}" },');
  }
  linesOut.add('  },');
  linesOut.add('};');
  linesOut.add('');
  return linesOut.join('\n');
}

/// Map an inferred variable type onto a schema type, dropping
/// `string`/`unknown` (nothing worth asserting).
String? _mapInferredType(VariableType ty) => switch (ty) {
      VariableType.integer => 'integer',
      VariableType.float => 'float',
      VariableType.boolean => 'boolean',
      VariableType.url => 'url',
      VariableType.json => 'json',
      _ => null,
    };

/// Infer a schema type from a single source line's access pattern.
String? _inferFromLine(String name, String line) {
  final escaped = RegExp.escape(name);
  final access = 'process\\.env\\.$escaped|import\\.meta\\.env\\.$escaped';

  if (RegExp('(parseInt|Number\\.parseInt)\\s*\\(\\s*($access)').hasMatch(line)) {
    return 'integer';
  }
  if (RegExp('(Number\\s*\\(\\s*($access)\\s*\\)|parseFloat|Number\\.parseFloat)\\s*\\(\\s*($access)')
      .hasMatch(line)) {
    return 'float';
  }
  if (RegExp('($access)\\s*===?\\s*[""\']true[""\']|($access)\\s*===?\\s*[""\']false[""\']|Boolean\\s*\\(\\s*($access)')
      .hasMatch(line)) {
    return 'boolean';
  }
  if (RegExp('JSON\\.parse\\s*\\(\\s*($access)').hasMatch(line)) {
    return 'json';
  }
  return null;
}

/// Generate a JSON schema for envdoctor configuration.
String generateConfigSchema() {
  JsonObject stringArrayProp(String description) => JsonObject()
    ..add('type', 'array')
    ..add('items', JsonObject()..add('type', 'string'))
    ..add('description', description);

  return jsonPretty(JsonObject()
    ..add(r'$schema', 'http://json-schema.org/draft-07/schema#')
    ..add('title', 'envdoctor configuration')
    ..add('type', 'object')
    ..add('additionalProperties', false)
    ..add('properties', JsonObject()
      ..add('envFilePatterns', stringArrayProp('Glob patterns for dotenv files'))
      ..add('composeFilePatterns', stringArrayProp('Glob patterns for docker-compose files'))
      ..add('actionsFilePatterns', stringArrayProp('Glob patterns for GitHub Actions workflows'))
      ..add('k8sFilePatterns', stringArrayProp('Glob patterns for Kubernetes manifests'))
      ..add('sourceExtensions', stringArrayProp('File extensions to scan for source usage'))
      ..add('ignoreVariables', stringArrayProp('Glob patterns of variable names to never report'))
      ..add('ignoreFiles', stringArrayProp('Glob patterns of files to skip'))
      ..add('environments', JsonObject()
        ..add('type', 'object')
        ..add('additionalProperties', JsonObject()
          ..add('type', 'array')
          ..add('items', JsonObject()..add('type', 'string')))
        ..add('description', 'Environment label -> file glob mapping'))
      ..add('strict', JsonObject()
        ..add('type', 'boolean')
        ..add('description', 'Fail on warnings'))
      ..add('rules', JsonObject()
        ..add('type', 'object')
        ..add('additionalProperties', JsonObject()
          ..add('type', 'string')
          ..add('enum', ['error', 'warning', 'off']))
        ..add('description', 'Per-detector severity overrides'))
      ..add('schema', JsonObject()
        ..add('type', 'object')
        ..add('additionalProperties', JsonObject()..add(r'$ref', '#/definitions/variableSchema'))
        ..add('description', 'Per-variable validation schema')))
    ..add('definitions', JsonObject()
      ..add('variableSchema', JsonObject()
        ..add('type', 'object')
        ..add('additionalProperties', false)
        ..add('properties', JsonObject()
          ..add('type', JsonObject()
            ..add('type', 'string')
            ..add('enum', ['string', 'integer', 'float', 'boolean', 'url', 'json', 'enum', 'regex']))
          ..add('optional', JsonObject()..add('type', 'boolean'))
          ..add('enum', JsonObject()
            ..add('type', 'array')
            ..add('items', JsonObject()..add('type', 'string')))
          ..add('regex', JsonObject()..add('type', 'string'))
          ..add('min', JsonObject()..add('type', 'integer'))
          ..add('max', JsonObject()..add('type', 'integer'))))));
}

/// Generate a TOML config template with all options commented.
String generateConfigTemplate() => r'''
# envdoctor configuration
# All fields are optional; uncomment and adjust as needed.

# envFilePatterns = [".env", ".env.*"]
# composeFilePatterns = ["**/docker-compose*.y*ml", "**/compose*.y*ml"]
# actionsFilePatterns = [".github/workflows/**/*.y*ml"]
# k8sFilePatterns = [
#   "**/*.{deployment,service,statefulset,daemonset,cronjob,job,configmap,secret,ingress,pvc}.y*ml",
#   "**/k8s/**/*.y*ml",
#   "**/kubernetes/**/*.y*ml",
#   "**/manifests/**/*.y*ml",
#   "**/deploy/**/*.y*ml"
# ]
# sourceExtensions = ["ts", "tsx", "js", "jsx", "mjs", "cjs"]
# ignoreVariables = ["AWS_*", "GOOGLE_*"]
# ignoreFiles = ["**/vendor/**", "**/node_modules/**"]
# strict = false

# [environments]
# development = [".env.development", ".env.local"]
# production = [".env.production"]
# staging = [".env.staging"]

# [rules]
# unused = "off"
# "environment-diff" = "warn"

# [schema]
# PORT = { type = "integer", min = 1, max = 65535 }
# NODE_ENV = { type = "enum", enum = ["development", "production", "test"] }
# DATABASE_URL = { type = "url" }
# LOG_LEVEL = { type = "enum", enum = ["debug", "info", "warn", "error"] }
# CONFIG_JSON = { type = "json" }
# ID_PATTERN = { type = "regex", regex = "^[A-Z_]+$" }
''';
