using Envdoctor.Config;
using Envdoctor.Models;
using Envdoctor.Utils;

namespace Envdoctor.Generators;

public static class EnvExampleGenerator
{
    /// Generate a deterministic `.env.example` for a project.
    ///
    /// - Secret-like names always get a blank value.
    /// - Non-secret values are copied ONLY from the base `.env` (development)
    ///   file; never from `.env.production`, `.env.local`, etc., and never a
    ///   secret value.
    public static string GenerateEnvExample(ProjectModel model, EnvdoctorConfig config)
    {
        // Names the app actually consumes (source + compose + actions).
        var used = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var file in model.SourceFiles.Concat(model.ComposeFiles).Concat(model.ActionFiles))
        {
            foreach (var v in file.Variables)
                used.Add(v.Name);
            foreach (var v in file.Usages)
                used.Add(v.Name);
        }

        // Names defined in environment files (including `.env.example`).
        var defined = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var file in model.EnvFiles)
        {
            foreach (var v in file.Variables)
                defined.Add(v.Name);
        }

        var required = used;
        var optional = defined.Where(n => !used.Contains(n)).ToList();

        var lines = new List<string>
        {
            "# .env.example",
            "# Generated by envdoctor. Copy to .env and fill in real values.",
            "# Secret values are intentionally left blank — never commit secrets.",
            "",
        };

        if (required.Count > 0)
        {
            lines.Add("# Required by the application");
            var names = required.ToList();
            Locale.LocaleSort(names);
            foreach (var name in names)
                lines.Add($"{name}={ValueFor(model, name)}");
            lines.Add("");
        }

        if (optional.Count > 0)
        {
            lines.Add("# Optional / configuration knobs");
            var names = optional;
            Locale.LocaleSort(names);
            foreach (var name in names)
                lines.Add($"{name}={ValueFor(model, name)}");
            lines.Add("");
        }

        return string.Join("\n", lines);
    }

    /// The value written for a name: blank for secrets, else the non-empty
    /// value from the development `.env`, else blank.
    private static string ValueFor(ProjectModel model, string name)
    {
        if (EnvironmentVariable.IsSecretName(name))
            return "";
        foreach (var file in model.EnvFiles)
        {
            if (file.Environment != "development")
                continue;
            var v = file.Variables.FirstOrDefault(v => v.Name == name && (v.Value ?? "").Length > 0);
            if (v is not null)
                return v.Value ?? "";
        }
        return "";
    }
}
