using Envdoctor.Config;
using Envdoctor.Models;
using Envdoctor.Utils;

namespace Envdoctor.Generators;

/// Generates `ENVIRONMENT.md`. Names only — no values ever appear. Note the
/// reference sorts the overview / per-environment lists with `localeCompare`
/// but the "missing" list and environment labels with the default (code-unit)
/// sort; both are reproduced here.
public static class EnvironmentDocGenerator
{
    private sealed class NameInfo
    {
        public string? Ty;
        public List<string> Environments = new();
        public bool UsedInSource;
        public bool IsSecret;
    }

    private sealed class NamesIndex
    {
        public List<string> Sorted = new();
        public Dictionary<string, NameInfo> Info = new();
        public List<string> Missing = new();
    }

    public static string GenerateEnvironmentDoc(ProjectModel model, EnvdoctorConfig config)
    {
        var names = CollectNames(model);

        var lines = new List<string>
        {
            "# Environment Variables",
            "",
            "> Generated by envdoctor. Do not edit by hand — run `envdoctor fix` to regenerate.",
            "",
        };

        // ---- Overview table ----
        lines.Add("## Overview");
        lines.Add("");
        lines.Add("| Variable | Type | Defined in | Used in source | Secret |");
        lines.Add("| --- | --- | --- | --- | --- |");
        foreach (var name in names.Sorted)
        {
            names.Info.TryGetValue(name, out var info);
            var ty = info?.Ty ?? "unknown";
            var envs = info is not null && info.Environments.Count > 0
                ? string.Join(", ", info.Environments)
                : "—";
            var source = info?.UsedInSource == true ? "✓" : "—";
            var secret = info?.IsSecret == true ? "✓" : "—";
            lines.Add($"| {name} | {ty} | {envs} | {source} | {secret} |");
        }
        lines.Add("");

        // ---- Missing ----
        if (names.Missing.Count > 0)
        {
            lines.Add("## Referenced but not defined");
            lines.Add("");
            lines.Add("These variables are expected somewhere in the project but are not defined in any environment file:");
            lines.Add("");
            foreach (var name in names.Missing)
                lines.Add($"- `{name}`");
            lines.Add("");
        }

        // ---- Per-environment sections ----
        lines.Add("## Environments");
        lines.Add("");
        var envLabels = DistinctEnvLabels(model);
        if (envLabels.Count == 0)
        {
            lines.Add("No environment files found.");
            lines.Add("");
        }
        else
        {
            foreach (var label in envLabels)
            {
                var files = model.EnvFiles
                    .Where(file => file.Environment == label)
                    .Select(file => $"`{file.FilePath}`")
                    .ToList();
                lines.Add($"### {label}");
                lines.Add("");
                lines.Add(files.Count > 0 ? $"Defined in {string.Join(", ", files)}." : "");
                foreach (var name in names.Sorted)
                {
                    if (names.Info.TryGetValue(name, out var info) &&
                        info.Environments.Count > 0 &&
                        info.Environments.Contains(label))
                    {
                        lines.Add($"- {name}");
                    }
                }
                lines.Add("");
            }
        }

        return string.Join("\n", lines);
    }

    private static NamesIndex CollectNames(ProjectModel model)
    {
        var names = new HashSet<string>();
        var info = new Dictionary<string, NameInfo>();
        var exampleNames = new HashSet<string>();

        // Definitions from environment files. `.env.example` is documentation —
        // it does not count as a real environment.
        foreach (var file in model.EnvFiles)
        {
            foreach (var v in file.Variables)
            {
                names.Add(v.Name);
                if (file.Environment == "example")
                {
                    exampleNames.Add(v.Name);
                    continue;
                }
                if (!info.TryGetValue(v.Name, out var entry))
                    info[v.Name] = entry = new NameInfo { IsSecret = v.IsSecret };
                if (file.Environment is not null && !entry.Environments.Contains(file.Environment))
                    entry.Environments.Add(file.Environment);
                if (entry.Ty is null && v.VarType != VariableType.Unknown)
                    entry.Ty = v.VarType.AsStr();
                entry.IsSecret |= v.IsSecret;
            }
        }

        // Source usages.
        var sourceUsed = new HashSet<string>();
        foreach (var file in model.SourceFiles)
        {
            foreach (var v in file.Usages)
            {
                names.Add(v.Name);
                sourceUsed.Add(v.Name);
            }
        }

        // Compose definitions and usages (GitHub Actions is intentionally excluded).
        var composeRefs = new HashSet<string>();
        foreach (var file in model.ComposeFiles)
        {
            foreach (var v in file.Variables)
            {
                names.Add(v.Name);
                composeRefs.Add(v.Name);
                if (!info.TryGetValue(v.Name, out var entry))
                    info[v.Name] = entry = new NameInfo { IsSecret = v.IsSecret };
                entry.IsSecret |= v.IsSecret;
            }
            foreach (var v in file.Usages)
            {
                names.Add(v.Name);
                composeRefs.Add(v.Name);
            }
        }

        foreach (var name in sourceUsed)
        {
            if (!info.TryGetValue(name, out var entry))
                info[name] = entry = new NameInfo();
            entry.UsedInSource = true;
        }

        // Referenced but not defined in any real environment file.
        var missing = names
            .Where(n =>
            {
                if (info.TryGetValue(n, out var i) && i.Environments.Count > 0)
                    return false;
                return sourceUsed.Contains(n) || composeRefs.Contains(n) || exampleNames.Contains(n);
            })
            .ToList();
        missing.Sort(StringComparer.Ordinal); // default (code-unit) order

        var sorted = names.ToList();
        Locale.LocaleSort(sorted);

        return new NamesIndex { Sorted = sorted, Info = info, Missing = missing };
    }

    private static List<string> DistinctEnvLabels(ProjectModel model)
    {
        var labels = new HashSet<string>();
        foreach (var file in model.EnvFiles)
        {
            if (file.Environment is not null && file.Environment != "example")
                labels.Add(file.Environment);
        }
        var result = labels.ToList();
        result.Sort(StringComparer.Ordinal); // default (code-unit) order
        return result;
    }
}
