using Envdoctor.Config;
using Envdoctor.Models;
using Envdoctor.Utils;

namespace Envdoctor.Generators;

public static class EnvTypesGenerator
{
    /// Generate a TypeScript ambient declaration for `NodeJS.ProcessEnv`.
    /// Values are never emitted — only names, plus inferred type / secret
    /// hints as JSDoc.
    public static string GenerateEnvTypes(ProjectModel model, EnvdoctorConfig config)
    {
        var names = new Dictionary<string, (bool IsSecret, string? InferredType)>();

        foreach (var file in model.AllFiles)
        {
            foreach (var v in file.Variables)
            {
                if (!names.TryGetValue(v.Name, out var existing))
                {
                    names[v.Name] = (
                        v.IsSecret,
                        v.VarType == VariableType.Unknown ? null : v.VarType.AsStr());
                }
                else if (v.VarType != VariableType.Unknown && existing.InferredType is null)
                {
                    names[v.Name] = (existing.IsSecret, v.VarType.AsStr());
                }
            }
            foreach (var v in file.Usages)
            {
                if (!names.ContainsKey(v.Name))
                    names[v.Name] = (v.IsSecret, null);
            }
        }

        var lines = new List<string>
        {
            "// Generated by envdoctor. Do not edit manually.",
            "// This file declares types for process.env variables.",
            "// Secret values are never included.",
            "",
            "declare global {",
            "  namespace NodeJS {",
            "    interface ProcessEnv {",
        };

        var sortedNames = names.Keys.ToList();
        Locale.LocaleSort(sortedNames);
        foreach (var name in sortedNames)
        {
            var meta = names[name];
            var docParts = new List<string>();
            if (meta.IsSecret)
                docParts.Add("secret");
            if (meta.InferredType is { } t)
                docParts.Add($"inferred type: {t}");
            if (docParts.Count > 0)
                lines.Add($"      /** {string.Join(" · ", docParts)} */");
            lines.Add($"      {name}: string;");
        }

        lines.Add("    }");
        lines.Add("  }");
        lines.Add("}");
        lines.Add("");
        lines.Add("export {};");
        lines.Add("");

        return string.Join("\n", lines);
    }
}
