using System.Text;
using Envdoctor.Config;
using Envdoctor.Models;
using Envdoctor.Utils;

namespace Envdoctor.Generators;

public sealed class ActionsChecklist
{
    /// Names referenced via `${{ secrets.X }}`.
    public List<string> Secrets { get; set; } = new();
    /// Names referenced via `${{ vars.X }}`.
    public List<string> Vars { get; set; } = new();
}

public static class GithubActionsGenerator
{
    /// Collect the repository secrets and variables referenced by a project's
    /// GitHub Actions workflows.
    public static ActionsChecklist CollectActionsChecklist(ProjectModel model)
    {
        var secrets = new SortedSet<string>(StringComparer.Ordinal);
        var vars = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var file in model.ActionFiles)
        {
            foreach (var usage in file.Usages)
            {
                foreach (var origin in usage.Origins)
                {
                    switch (origin.Subkind)
                    {
                        case "vars":
                            vars.Add(usage.Name);
                            break;
                        case "secrets":
                            secrets.Add(usage.Name);
                            break;
                    }
                }
            }
        }

        return new ActionsChecklist { Secrets = secrets.ToList(), Vars = vars.ToList() };
    }

    /// Generate `.github/ENVIRONMENT.md` — a checklist of the repository
    /// secrets and variables that must be configured for the workflows to
    /// work. Names only; values are never mentioned.
    public static string GenerateActionsChecklist(ProjectModel model)
    {
        var checklist = CollectActionsChecklist(model);

        var lines = new List<string> { "# GitHub Actions environment checklist" };
        lines.Add("");
        lines.Add("> Generated by envdoctor. Do not edit by hand.");
        lines.Add("");
        lines.Add("Configure these repository secrets and variables (Settings → Secrets and variables → Actions).");
        lines.Add("");

        lines.Add("## Secrets");
        if (checklist.Secrets.Count == 0)
        {
            lines.Add("None.");
        }
        else
        {
            foreach (var name in checklist.Secrets)
                lines.Add($"- [ ] `{name}`");
        }
        lines.Add("");

        lines.Add("## Variables");
        if (checklist.Vars.Count == 0)
        {
            lines.Add("None.");
        }
        else
        {
            foreach (var name in checklist.Vars)
                lines.Add($"- [ ] `{name}`");
        }
        lines.Add("");

        return string.Join("\n", lines);
    }

    /// Generate a GitHub Actions workflow snippet with env vars from the model.
    public static string GenerateGithubActions(ProjectModel model, EnvdoctorConfig config)
    {
        var byName = new Dictionary<string, EnvironmentVariable>();

        // Prefer env file definitions, then compose, then actions, then k8s
        foreach (var files in new[]
        {
            model.EnvFiles, model.ComposeFiles, model.ActionFiles, model.K8sFiles,
        })
        {
            foreach (var file in files)
            {
                foreach (var v in file.Variables)
                {
                    if (config.IgnoreVariables.Count > 0 &&
                        Glob.MatchesAnyGlob(config.IgnoreVariables, v.Name))
                    {
                        continue;
                    }
                    if (!byName.ContainsKey(v.Name))
                        byName[v.Name] = v;
                }
            }
        }

        var names = byName.Keys.ToList();
        names.Sort(StringComparer.Ordinal);

        var outSb = new StringBuilder();
        outSb.Append("# Generated by envdoctor — add to your workflow.\n");
        outSb.Append("# Replace ${{ secrets.X }} with your actual secret names.\n\n");

        // Separate secrets from regular vars
        var secrets = new List<string>();
        var regular = new List<string>();

        foreach (var name in names)
        {
            if (byName[name].IsSecret)
                secrets.Add(name);
            else
                regular.Add(name);
        }

        if (regular.Count == 0 && secrets.Count == 0)
            return outSb.ToString();

        outSb.Append("env:\n");
        foreach (var name in regular)
        {
            var val = byName[name].Value ?? "REPLACE_ME";
            // Escape for YAML
            var escaped = val.Replace("\"", "\\\"");
            outSb.Append($"  {name}: \"{escaped}\"\n");
        }
        foreach (var name in secrets)
        {
            outSb.Append($"  {name}: ${{{{ secrets.{name.ToUpperInvariant()} }}}}\n");
        }
        outSb.Append('\n');

        return outSb.ToString();
    }
}
