using System.Text.RegularExpressions;
using Envdoctor.Models;
using Envdoctor.Utils;

namespace Envdoctor.Generators;

public static class SchemaGenerator
{
    /// Infer a validation schema for every known environment variable by
    /// inspecting existing env values and source-code usage patterns, then
    /// emit it as a TypeScript module (`envdoctor.schema.ts`).
    public static string GenerateVariableSchemaTs(ProjectModel model)
    {
        // name → type string (e.g. "integer")
        var schema = new SortedDictionary<string, string>(StringComparer.Ordinal);

        // Infer from existing env values first.
        foreach (var file in model.EnvFiles)
        {
            foreach (var v in file.Variables)
            {
                if (v.Value is null)
                    continue;
                if (MapInferredType(TypeInfer.InferType(v.Value)) is { } mapped)
                    schema[v.Name] = mapped;
            }
        }

        // Refine from source usage patterns.
        foreach (var file in model.SourceFiles)
        {
            string content;
            try
            {
                content = File.ReadAllText(file.FilePath);
            }
            catch
            {
                continue;
            }
            var lines = content.Split('\n');
            foreach (var usage in file.Usages)
            {
                foreach (var origin in usage.Origins)
                {
                    if (origin.Line is not { } lineNo)
                        continue;
                    var line = lineNo - 1 >= 0 && lineNo - 1 < lines.Length ? lines[lineNo - 1] : "";
                    if (InferFromLine(usage.Name, line) is { } inferred)
                        schema[usage.Name] = inferred;
                }
            }
        }

        if (schema.Count == 0)
            return "// Generated by envdoctor. No schema could be inferred.\nexport default {\n  schema: {},\n};\n";

        var linesOut = new List<string> { "// Generated by envdoctor. Merge into envdoctor.config.ts:" };
        linesOut.Add("// import schema from './envdoctor.schema'; export default { ..., ...schema };");
        linesOut.Add("");
        linesOut.Add("export default {");
        linesOut.Add("  schema: {");
        // Match the TS reference: entries are ordered by `localeCompare`, not
        // byte order.
        var entries = schema.ToList();
        entries.Sort((a, b) => Locale.LocaleCompare(a.Key, b.Key));
        foreach (var (name, ty) in entries)
            linesOut.Add($"    {name}: {{ type: \"{ty}\" }},");
        linesOut.Add("  },");
        linesOut.Add("};");
        linesOut.Add("");
        return string.Join("\n", linesOut);
    }

    /// Map an inferred variable type onto a schema type, dropping
    /// `string`/`unknown` (nothing worth asserting).
    private static string? MapInferredType(VariableType ty) => ty switch
    {
        VariableType.Integer => "integer",
        VariableType.Float => "float",
        VariableType.Boolean => "boolean",
        VariableType.Url => "url",
        VariableType.Json => "json",
        _ => null,
    };

    /// Infer a schema type from a single source line's access pattern.
    private static string? InferFromLine(string name, string line)
    {
        var escaped = Regex.Escape(name);
        var access = $@"process\.env\.{escaped}|import\.meta\.env\.{escaped}";

        if (Regex.IsMatch(line, $@"(parseInt|Number\.parseInt)\s*\(\s*({access})"))
            return "integer";
        if (Regex.IsMatch(line, $@"(Number\s*\(\s*({access})\s*\)|parseFloat|Number\.parseFloat)\s*\(\s*({access})"))
            return "float";
        if (Regex.IsMatch(line, $@"({access})\s*===?\s*[""']true[""']|({access})\s*===?\s*[""']false[""']|Boolean\s*\(\s*({access})"))
            return "boolean";
        if (Regex.IsMatch(line, $@"JSON\.parse\s*\(\s*({access})"))
            return "json";
        return null;
    }

    /// Generate a JSON schema for envdoctor configuration.
    public static string GenerateConfigSchema()
    {
        static JsonObject StringArrayProp(string description) => new()
        {
            { "type", "array" },
            { "items", new JsonObject { { "type", "string" } } },
            { "description", description },
        };

        return Json.Pretty(new JsonObject
        {
            { "$schema", "http://json-schema.org/draft-07/schema#" },
            { "title", "envdoctor configuration" },
            { "type", "object" },
            { "additionalProperties", false },
            {
                "properties", new JsonObject
                {
                    { "envFilePatterns", StringArrayProp("Glob patterns for dotenv files") },
                    { "composeFilePatterns", StringArrayProp("Glob patterns for docker-compose files") },
                    { "actionsFilePatterns", StringArrayProp("Glob patterns for GitHub Actions workflows") },
                    { "k8sFilePatterns", StringArrayProp("Glob patterns for Kubernetes manifests") },
                    { "sourceExtensions", StringArrayProp("File extensions to scan for source usage") },
                    { "ignoreVariables", StringArrayProp("Glob patterns of variable names to never report") },
                    { "ignoreFiles", StringArrayProp("Glob patterns of files to skip") },
                    {
                        "environments", new JsonObject
                        {
                            { "type", "object" },
                            {
                                "additionalProperties", new JsonObject
                                {
                                    { "type", "array" },
                                    { "items", new JsonObject { { "type", "string" } } },
                                }
                            },
                            { "description", "Environment label -> file glob mapping" },
                        }
                    },
                    {
                        "strict", new JsonObject
                        {
                            { "type", "boolean" },
                            { "description", "Fail on warnings" },
                        }
                    },
                    {
                        "rules", new JsonObject
                        {
                            { "type", "object" },
                            {
                                "additionalProperties", new JsonObject
                                {
                                    { "type", "string" },
                                    { "enum", new List<object?> { "error", "warning", "off" } },
                                }
                            },
                            { "description", "Per-detector severity overrides" },
                        }
                    },
                    {
                        "schema", new JsonObject
                        {
                            { "type", "object" },
                            { "additionalProperties", new JsonObject { { "$ref", "#/definitions/variableSchema" } } },
                            { "description", "Per-variable validation schema" },
                        }
                    },
                }
            },
            {
                "definitions", new JsonObject
                {
                    {
                        "variableSchema", new JsonObject
                        {
                            { "type", "object" },
                            { "additionalProperties", false },
                            {
                                "properties", new JsonObject
                                {
                                    {
                                        "type", new JsonObject
                                        {
                                            { "type", "string" },
                                            {
                                                "enum", new List<object?>
                                                {
                                                    "string", "integer", "float", "boolean",
                                                    "url", "json", "enum", "regex",
                                                }
                                            },
                                        }
                                    },
                                    { "optional", new JsonObject { { "type", "boolean" } } },
                                    {
                                        "enum", new JsonObject
                                        {
                                            { "type", "array" },
                                            { "items", new JsonObject { { "type", "string" } } },
                                        }
                                    },
                                    { "regex", new JsonObject { { "type", "string" } } },
                                    { "min", new JsonObject { { "type", "integer" } } },
                                    { "max", new JsonObject { { "type", "integer" } } },
                                }
                            },
                        }
                    },
                }
            },
        });
    }

    /// Generate a TOML config template with all options commented.
    public static string GenerateConfigTemplate() =>
"""
# envdoctor configuration
# All fields are optional; uncomment and adjust as needed.

# envFilePatterns = [".env", ".env.*"]
# composeFilePatterns = ["**/docker-compose*.y*ml", "**/compose*.y*ml"]
# actionsFilePatterns = [".github/workflows/**/*.y*ml"]
# k8sFilePatterns = [
#   "**/*.{deployment,service,statefulset,daemonset,cronjob,job,configmap,secret,ingress,pvc}.y*ml",
#   "**/k8s/**/*.y*ml",
#   "**/kubernetes/**/*.y*ml",
#   "**/manifests/**/*.y*ml",
#   "**/deploy/**/*.y*ml"
# ]
# sourceExtensions = ["ts", "tsx", "js", "jsx", "mjs", "cjs"]
# ignoreVariables = ["AWS_*", "GOOGLE_*"]
# ignoreFiles = ["**/vendor/**", "**/node_modules/**"]
# strict = false

# [environments]
# development = [".env.development", ".env.local"]
# production = [".env.production"]
# staging = [".env.staging"]

# [rules]
# unused = "off"
# "environment-diff" = "warn"

# [schema]
# PORT = { type = "integer", min = 1, max = 65535 }
# NODE_ENV = { type = "enum", enum = ["development", "production", "test"] }
# DATABASE_URL = { type = "url" }
# LOG_LEVEL = { type = "enum", enum = ["debug", "info", "warn", "error"] }
# CONFIG_JSON = { type = "json" }
# ID_PATTERN = { type = "regex", regex = "^[A-Z_]+$" }

""";
}
