use crate::models::{EnvironmentVariable, VariableType};
use std::collections::HashMap;

/// Generate TypeScript/JS type definitions (`env.d.ts`) from the model.
pub fn generate_env_types(
    model: &crate::models::ProjectModel,
    config: &crate::config::EnvdoctorConfig,
) -> String {
    let mut by_name: HashMap<String, &EnvironmentVariable> = HashMap::new();

    for file in &model.all_files {
        for v in &file.variables {
            if !config.ignore_variables.is_empty()
                && crate::utils::glob::matches_any_glob(&config.ignore_variables, &v.name)
            {
                continue;
            }
            by_name.entry(v.name.clone()).or_insert(v);
        }
    }

    let mut names: Vec<&String> = by_name.keys().collect();
    names.sort();

    let mut out = String::new();
    out.push_str("// Generated by envdoctor — do not edit directly.\n");
    out.push_str("// Run `envdoctor generate env-types` to update.\n\n");

    // For Vite/Next.js style, use ImportMetaEnv
    let has_vite = names.iter().any(|n| n.starts_with("VITE_"));
    let has_next = names.iter().any(|n| n.starts_with("NEXT_PUBLIC_"));
    let has_react = names.iter().any(|n| n.starts_with("REACT_APP_"));

    if has_vite || has_next || has_react {
        // Generate interface
        if has_vite {
            out.push_str("interface ImportMetaEnv {\n");
        } else if has_next {
            out.push_str("interface ProcessEnv {\n");
        } else {
            out.push_str("interface ProcessEnv {\n");
        }

        for name in &names {
            let v = by_name[*name];
            let ts_type = variable_type_to_ts(&v.var_type, v.value.as_deref());
            let optional = if v.value.is_none() { "?" } else { "" };
            let comment = if v.is_secret { " // secret" } else { "" };
            out.push_str(&format!("  readonly {}{}: {}{}\n", name, optional, ts_type, comment));
        }
        out.push_str("}\n\n");

        if has_vite {
            out.push_str("interface ImportMeta {\n");
            out.push_str("  readonly env: ImportMetaEnv;\n");
            out.push_str("}\n");
        }
    } else {
        // Node.js ProcessEnv style
        out.push_str("declare namespace NodeJS {\n");
        out.push_str("  interface ProcessEnv {\n");
        for name in &names {
            let v = by_name[*name];
            let ts_type = variable_type_to_ts(&v.var_type, v.value.as_deref());
            let optional = if v.value.is_none() { "?" } else { "" };
            let comment = if v.is_secret { " // secret" } else { "" };
            out.push_str(&format!("    {}{}: {}{}\n", name, optional, ts_type, comment));
        }
        out.push_str("  }\n");
        out.push_str("}\n");
    }

    out
}

fn variable_type_to_ts(var_type: &VariableType, value: Option<&str>) -> String {
    match var_type {
        VariableType::String => "string".to_string(),
        VariableType::Integer => "number".to_string(),
        VariableType::Float => "number".to_string(),
        VariableType::Boolean => "boolean".to_string(),
        VariableType::Url => "string".to_string(),
        VariableType::Json => "string".to_string(), // JSON is a string in env
        VariableType::Unknown => {
            // Try to infer from value
            value.map_or("string".to_string(), infer_ts_type)
        }
    }
}

fn infer_ts_type(value: &str) -> String {
    let v = value.trim();
    if v.parse::<i64>().is_ok() {
        "number".to_string()
    } else if v.parse::<f64>().is_ok() {
        "number".to_string()
    } else if v == "true" || v == "false" {
        "boolean".to_string()
    } else if v.starts_with("http://") || v.starts_with("https://") {
        "string".to_string()
    } else if (v.starts_with('{') && v.ends_with('}'))
        || (v.starts_with('[') && v.ends_with(']'))
    {
        "string".to_string()
    } else {
        "string".to_string()
    }
}