use crate::config::EnvdoctorConfig;
use crate::models::{EnvironmentVariable, ProjectModel};
use crate::utils::locale::locale_sort;
use std::collections::BTreeSet;

/// Generate a deterministic `.env.example` for a project.
///
/// Port of the TypeScript reference (`src/generators/env-example.ts`):
/// - Secret-like names always get a blank value.
/// - Non-secret values are copied ONLY from the base `.env` (development) file;
///   never from `.env.production`, `.env.local`, etc., and never a secret value.
pub fn generate_env_example(model: &ProjectModel, _config: &EnvdoctorConfig) -> String {
    // Names the app actually consumes (source + compose + actions).
    let mut used: BTreeSet<String> = BTreeSet::new();
    for file in model
        .source_files
        .iter()
        .chain(&model.compose_files)
        .chain(&model.action_files)
    {
        for v in &file.variables {
            used.insert(v.name.clone());
        }
        for v in &file.usages {
            used.insert(v.name.clone());
        }
    }

    // Names defined in environment files (including `.env.example`).
    let mut defined: BTreeSet<String> = BTreeSet::new();
    for file in &model.env_files {
        for v in &file.variables {
            defined.insert(v.name.clone());
        }
    }

    let required = &used;
    let optional: Vec<String> = defined
        .iter()
        .filter(|n| !used.contains(*n))
        .cloned()
        .collect();

    let mut lines: Vec<String> = vec![
        "# .env.example".to_string(),
        "# Generated by envdoctor. Copy to .env and fill in real values.".to_string(),
        "# Secret values are intentionally left blank — never commit secrets.".to_string(),
        String::new(),
    ];

    if !required.is_empty() {
        lines.push("# Required by the application".to_string());
        let mut names: Vec<String> = required.iter().cloned().collect();
        locale_sort(&mut names);
        for name in &names {
            lines.push(format!("{}={}", name, value_for(model, name)));
        }
        lines.push(String::new());
    }

    if !optional.is_empty() {
        lines.push("# Optional / configuration knobs".to_string());
        let mut names = optional;
        locale_sort(&mut names);
        for name in &names {
            lines.push(format!("{}={}", name, value_for(model, name)));
        }
        lines.push(String::new());
    }

    lines.join("\n")
}

/// The value written for a name: blank for secrets, else the non-empty value
/// from the development `.env`, else blank.
fn value_for(model: &ProjectModel, name: &str) -> String {
    if EnvironmentVariable::is_secret_name(name) {
        return String::new();
    }
    for file in &model.env_files {
        if file.environment.as_deref() != Some("development") {
            continue;
        }
        if let Some(v) = file
            .variables
            .iter()
            .find(|v| v.name == name && !v.value.as_deref().unwrap_or("").is_empty())
        {
            return v.value.clone().unwrap_or_default();
        }
    }
    String::new()
}
