use crate::config::EnvdoctorConfig;
use crate::models::ProjectModel;
use crate::utils::locale::locale_sort;
use std::collections::HashMap;

/// Generate a TypeScript ambient declaration for `NodeJS.ProcessEnv`.
///
/// Port of the TypeScript reference (`src/generators/env-types.ts`). Values are
/// never emitted — only names, plus inferred type / secret hints as JSDoc.
pub fn generate_env_types(model: &ProjectModel, _config: &EnvdoctorConfig) -> String {
    struct Meta {
        is_secret: bool,
        inferred_type: Option<String>,
    }
    let mut names: HashMap<String, Meta> = HashMap::new();

    for file in &model.all_files {
        for v in &file.variables {
            match names.get_mut(&v.name) {
                None => {
                    names.insert(
                        v.name.clone(),
                        Meta {
                            is_secret: v.is_secret,
                            inferred_type: if v.var_type == crate::models::VariableType::Unknown {
                                None
                            } else {
                                Some(v.var_type.as_str().to_string())
                            },
                        },
                    );
                }
                Some(existing) => {
                    if v.var_type != crate::models::VariableType::Unknown
                        && existing.inferred_type.is_none()
                    {
                        existing.inferred_type = Some(v.var_type.as_str().to_string());
                    }
                }
            }
        }
        for v in &file.usages {
            names.entry(v.name.clone()).or_insert(Meta {
                is_secret: v.is_secret,
                inferred_type: None,
            });
        }
    }

    let mut lines: Vec<String> = vec![
        "// Generated by envdoctor. Do not edit manually.".to_string(),
        "// This file declares types for process.env variables.".to_string(),
        "// Secret values are never included.".to_string(),
        String::new(),
        "declare global {".to_string(),
        "  namespace NodeJS {".to_string(),
        "    interface ProcessEnv {".to_string(),
    ];

    let mut sorted_names: Vec<String> = names.keys().cloned().collect();
    locale_sort(&mut sorted_names);
    for name in &sorted_names {
        let meta = &names[name];
        let mut doc_parts: Vec<String> = Vec::new();
        if meta.is_secret {
            doc_parts.push("secret".to_string());
        }
        if let Some(t) = &meta.inferred_type {
            doc_parts.push(format!("inferred type: {t}"));
        }
        if !doc_parts.is_empty() {
            lines.push(format!("      /** {} */", doc_parts.join(" · ")));
        }
        lines.push(format!("      {name}: string;"));
    }

    lines.push("    }".to_string());
    lines.push("  }".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push("export {};".to_string());
    lines.push(String::new());

    lines.join("\n")
}
