use crate::models::EnvironmentVariable;
use crate::utils::glob::matches_any_glob;
use std::collections::{HashMap, HashSet};

/// Generate `.env.example` content from the model.
///
/// Includes all variables defined in env files (not compose/actions/k8s)
/// that are not ignored, sorted alphabetically, with placeholder comments.
pub fn generate_env_example(
    model: &crate::models::ProjectModel,
    config: &crate::config::EnvdoctorConfig,
) -> String {
    let mut by_name: HashMap<String, &EnvironmentVariable> = HashMap::new();

    for file in &model.env_files {
        for v in &file.variables {
            // Skip ignored
            if !config.ignore_variables.is_empty()
                && matches_any_glob(&config.ignore_variables, &v.name)
            {
                continue;
            }
            // Keep the first definition we see (alphabetically by file)
            by_name.entry(v.name.clone()).or_insert(v);
        }
    }

    let mut names: Vec<&String> = by_name.keys().collect();
    names.sort();

    let mut out = String::new();
    out.push_str("# Generated by envdoctor — commit this file.\n");
    out.push_str("# Values are placeholders; replace with real values.\n\n");

    for name in names {
        let v = by_name[name];
        // Add a comment if it looks like a secret
        if v.is_secret {
            out.push_str(&format!("{}={}\n", name, placeholder_for_secret(name)));
        } else if let Some(val) = &v.value {
            // Use the actual value as a hint if it's not a secret
            out.push_str(&format!("{}={}\n", name, val));
        } else {
            out.push_str(&format!("{}={}\n", name, "CHANGE_ME"));
        }
    }

    out
}

fn placeholder_for_secret(name: &str) -> &'static str {
    let upper = name.to_uppercase();
    if upper.contains("PASSWORD") {
        "your_password_here"
    } else if upper.contains("SECRET") || upper.contains("TOKEN") {
        "your_secret_here"
    } else if upper.contains("API_KEY") || upper.contains("APIKEY") {
        "your_api_key_here"
    } else if upper.contains("PRIVATE_KEY") {
        "your_private_key_here"
    } else if upper.contains("CREDENTIAL") {
        "your_credentials_here"
    } else {
        "your_value_here"
    }
}

/// Generate a complete `.env.example` file with all environment variables
/// from all sources (env, compose, actions, k8s) for documentation purposes.
pub fn generate_env_example_all(
    model: &crate::models::ProjectModel,
    config: &crate::config::EnvdoctorConfig,
) -> String {
    let mut by_name: HashMap<String, Vec<&EnvironmentVariable>> = HashMap::new();

    for file in &model.all_files {
        for v in &file.variables {
            if !config.ignore_variables.is_empty()
                && matches_any_glob(&config.ignore_variables, &v.name)
            {
                continue;
            }
            by_name.entry(v.name.clone()).or_default().push(v);
        }
    }

    let mut names: Vec<&String> = by_name.keys().collect();
    names.sort();

    let mut out = String::new();
    out.push_str("# Generated by envdoctor — commit this file.\n");
    out.push_str("# Values are placeholders; replace with real values.\n\n");

    for name in names {
        let vars = &by_name[name];
        let v = vars[0]; // first definition

        // Add source comments
        let mut formats: Vec<&str> = vars.iter()
            .map(|v| match v.origins.first() {
                Some(o) => match o.format {
                    Some(crate::models::OriginFormat::Dotenv) => "dotenv",
                    Some(crate::models::OriginFormat::DockerCompose) => "compose",
                    Some(crate::models::OriginFormat::GithubActions) => "actions",
                    Some(crate::models::OriginFormat::Kubernetes) => "k8s",
                    Some(crate::models::OriginFormat::Source) => "source",
                    None => "unknown",
                },
                None => "unknown",
            })
            .collect::<HashSet<_>>()
            .into_iter()
            .collect();
        formats.sort();

        out.push_str(&format!("# Source: {}\n", formats.join(", ")));
        if v.is_secret {
            out.push_str(&format!("{}={}\n", name, placeholder_for_secret(name)));
        } else if let Some(val) = &v.value {
            out.push_str(&format!("{}={}\n", name, val));
        } else {
            out.push_str(&format!("{}={}\n", name, "CHANGE_ME"));
        }
        out.push('\n');
    }

    out
}