use crate::models::EnvironmentVariable;
use std::collections::HashMap;

/// Generate `ENVIRONMENT.md` documentation from the model.
pub fn generate_environment_doc(
    model: &crate::models::ProjectModel,
    config: &crate::config::EnvdoctorConfig,
) -> String {
    let mut by_name: HashMap<String, Vec<&EnvironmentVariable>> = HashMap::new();

    for file in &model.all_files {
        for v in &file.variables {
            if !config.ignore_variables.is_empty()
                && crate::utils::glob::matches_any_glob(&config.ignore_variables, &v.name)
            {
                continue;
            }
            by_name.entry(v.name.clone()).or_default().push(v);
        }
    }

    let mut names: Vec<&String> = by_name.keys().collect();
    names.sort();

    let mut out = String::new();
    out.push_str("# Environment Variables\n\n");
    out.push_str("This file is generated by [envdoctor](https://github.com/arun-skg/envdoctor).\n");
    out.push_str("Do not edit directly — run `envdoctor generate env-doc` to update.\n\n");
    out.push_str("---\n\n");

    // Group by source format
    let mut by_format: HashMap<&str, Vec<&String>> = HashMap::new();
    for name in &names {
        let vars = &by_name[*name];
        let format = vars[0].origins.first()
            .and_then(|o| o.format.clone())
            .map(|f| match f {
                crate::models::OriginFormat::Dotenv => "Dotenv (.env*)",
                crate::models::OriginFormat::DockerCompose => "Docker Compose",
                crate::models::OriginFormat::GithubActions => "GitHub Actions",
                crate::models::OriginFormat::Kubernetes => "Kubernetes",
                crate::models::OriginFormat::Source => "Source code",
            })
            .unwrap_or("Unknown");
        by_format.entry(format).or_default().push(*name);
    }

    // Order: dotenv, compose, actions, k8s, source
    let format_order = [
        "Dotenv (.env*)",
        "Docker Compose",
        "GitHub Actions",
        "Kubernetes",
        "Source code",
        "Unknown",
    ];

    for format in format_order {
        let Some(var_names) = by_format.get(format) else { continue };
        if var_names.is_empty() { continue; }

        out.push_str(&format!("## {}\n\n", format));
        out.push_str("| Variable | Type | Required | Secret | Description |\n");
        out.push_str("|----------|------|----------|--------|-------------|\n");

        for name in var_names {
            let vars = &by_name[*name];
            let v = vars[0];
            let var_type = format!("{:?}", v.var_type);
            let required = if v.value.is_some() { "Yes" } else { "No" };
            let secret = if v.is_secret { "Yes" } else { "No" };
            let desc = description_for(name, v);
            out.push_str(&format!("| {} | {} | {} | {} | {} |\n", name, var_type, required, secret, desc));
        }
        out.push('\n');
    }

    out
}

fn description_for(name: &str, _v: &EnvironmentVariable) -> String {
    let upper = name.to_uppercase();
    if upper.contains("DATABASE") || upper.contains("DB_") {
        "Database connection".to_string()
    } else if upper.contains("REDIS") {
        "Redis connection".to_string()
    } else if upper.contains("API") && upper.contains("KEY") {
        "API key for external service".to_string()
    } else if upper.contains("SECRET") || upper.contains("TOKEN") {
        "Authentication secret/token".to_string()
    } else if upper.contains("PASSWORD") || upper.contains("PASSWD") {
        "Password for service".to_string()
    } else if upper.contains("URL") || upper.contains("ENDPOINT") {
        "Service endpoint URL".to_string()
    } else if upper.contains("PORT") {
        "Network port".to_string()
    } else if upper.contains("HOST") {
        "Service hostname".to_string()
    } else if upper.contains("NODE_ENV") || upper.contains("ENV") {
        "Runtime environment (development/production/test)".to_string()
    } else if upper.contains("DEBUG") || upper.contains("LOG") {
        "Debug/logging configuration".to_string()
    } else {
        "No description available".to_string()
    }
}