use crate::config::EnvdoctorConfig;
use crate::models::{ProjectModel, VariableType};
use crate::utils::locale::locale_sort;
use std::collections::{HashMap, HashSet};

/// Port of the TypeScript reference (`src/generators/environment-doc.ts`).
///
/// Generates `ENVIRONMENT.md`. Names only — no values ever appear. Note the
/// reference sorts the overview / per-environment lists with `localeCompare`
/// but the "missing" list and environment labels with the default (code-unit)
/// sort; both are reproduced here.
pub fn generate_environment_doc(model: &ProjectModel, _config: &EnvdoctorConfig) -> String {
    let names = collect_names(model);

    let mut lines: Vec<String> = vec![
        "# Environment Variables".to_string(),
        String::new(),
        "> Generated by envdoctor. Do not edit by hand — run `envdoctor fix` to regenerate."
            .to_string(),
        String::new(),
    ];

    // ---- Overview table ----
    lines.push("## Overview".to_string());
    lines.push(String::new());
    lines.push("| Variable | Type | Defined in | Used in source | Secret |".to_string());
    lines.push("| --- | --- | --- | --- | --- |".to_string());
    for name in &names.sorted {
        let info = names.info.get(name);
        let ty = info
            .and_then(|i| i.ty.as_deref())
            .unwrap_or("unknown")
            .to_string();
        let envs = match info {
            Some(i) if !i.environments.is_empty() => i.environments.join(", "),
            _ => "—".to_string(),
        };
        let source = if info.map(|i| i.used_in_source).unwrap_or(false) {
            "✓"
        } else {
            "—"
        };
        let secret = if info.map(|i| i.is_secret).unwrap_or(false) {
            "✓"
        } else {
            "—"
        };
        lines.push(format!(
            "| {} | {} | {} | {} | {} |",
            name, ty, envs, source, secret
        ));
    }
    lines.push(String::new());

    // ---- Missing ----
    if !names.missing.is_empty() {
        lines.push("## Referenced but not defined".to_string());
        lines.push(String::new());
        lines.push(
            "These variables are expected somewhere in the project but are not defined in any environment file:"
                .to_string(),
        );
        lines.push(String::new());
        for name in &names.missing {
            lines.push(format!("- `{name}`"));
        }
        lines.push(String::new());
    }

    // ---- Per-environment sections ----
    lines.push("## Environments".to_string());
    lines.push(String::new());
    let env_labels = distinct_env_labels(model);
    if env_labels.is_empty() {
        lines.push("No environment files found.".to_string());
        lines.push(String::new());
    } else {
        for label in &env_labels {
            let files: Vec<String> = model
                .env_files
                .iter()
                .filter(|file| file.environment.as_deref() == Some(label.as_str()))
                .map(|file| format!("`{}`", file.file_path))
                .collect();
            lines.push(format!("### {label}"));
            lines.push(String::new());
            lines.push(if !files.is_empty() {
                format!("Defined in {}.", files.join(", "))
            } else {
                String::new()
            });
            for name in &names.sorted {
                if let Some(info) = names.info.get(name) {
                    if !info.environments.is_empty() && info.environments.contains(label) {
                        lines.push(format!("- {name}"));
                    }
                }
            }
            lines.push(String::new());
        }
    }

    lines.join("\n")
}

struct NameInfo {
    ty: Option<String>,
    environments: Vec<String>,
    used_in_source: bool,
    is_secret: bool,
}

struct NamesIndex {
    sorted: Vec<String>,
    info: HashMap<String, NameInfo>,
    missing: Vec<String>,
}

fn collect_names(model: &ProjectModel) -> NamesIndex {
    let mut names: HashSet<String> = HashSet::new();
    let mut info: HashMap<String, NameInfo> = HashMap::new();
    let mut example_names: HashSet<String> = HashSet::new();

    // Definitions from environment files. `.env.example` is documentation — it
    // does not count as a real environment.
    for file in &model.env_files {
        for v in &file.variables {
            names.insert(v.name.clone());
            if file.environment.as_deref() == Some("example") {
                example_names.insert(v.name.clone());
                continue;
            }
            let entry = info.entry(v.name.clone()).or_insert_with(|| NameInfo {
                ty: None,
                environments: Vec::new(),
                used_in_source: false,
                is_secret: v.is_secret,
            });
            if let Some(env) = &file.environment {
                if !entry.environments.contains(env) {
                    entry.environments.push(env.clone());
                }
            }
            if entry.ty.is_none() && v.var_type != VariableType::Unknown {
                entry.ty = Some(v.var_type.as_str().to_string());
            }
            entry.is_secret |= v.is_secret;
        }
    }

    // Source usages.
    let mut source_used: HashSet<String> = HashSet::new();
    for file in &model.source_files {
        for v in &file.usages {
            names.insert(v.name.clone());
            source_used.insert(v.name.clone());
        }
    }

    // Compose definitions and usages (GitHub Actions is intentionally excluded).
    let mut compose_refs: HashSet<String> = HashSet::new();
    for file in &model.compose_files {
        for v in &file.variables {
            names.insert(v.name.clone());
            compose_refs.insert(v.name.clone());
            let entry = info.entry(v.name.clone()).or_insert_with(|| NameInfo {
                ty: None,
                environments: Vec::new(),
                used_in_source: false,
                is_secret: v.is_secret,
            });
            entry.is_secret |= v.is_secret;
        }
        for v in &file.usages {
            names.insert(v.name.clone());
            compose_refs.insert(v.name.clone());
        }
    }

    for name in &source_used {
        let entry = info.entry(name.clone()).or_insert_with(|| NameInfo {
            ty: None,
            environments: Vec::new(),
            used_in_source: false,
            is_secret: false,
        });
        entry.used_in_source = true;
    }

    // Referenced but not defined in any real environment file.
    let mut missing: Vec<String> = names
        .iter()
        .filter(|n| {
            if info.get(*n).map(|i| i.environments.len()).unwrap_or(0) > 0 {
                return false;
            }
            source_used.contains(*n) || compose_refs.contains(*n) || example_names.contains(*n)
        })
        .cloned()
        .collect();
    missing.sort(); // default (code-unit) order, matching TS `.sort()`

    let mut sorted: Vec<String> = names.into_iter().collect();
    locale_sort(&mut sorted);

    NamesIndex {
        sorted,
        info,
        missing,
    }
}

fn distinct_env_labels(model: &ProjectModel) -> Vec<String> {
    let mut labels: HashSet<String> = HashSet::new();
    for file in &model.env_files {
        if let Some(env) = &file.environment {
            if env != "example" {
                labels.insert(env.clone());
            }
        }
    }
    let mut out: Vec<String> = labels.into_iter().collect();
    out.sort(); // default (code-unit) order, matching TS `.sort()`
    out
}
