use crate::models::{EnvironmentVariable, ProjectModel};
use std::collections::{BTreeSet, HashMap};

/// The repository secrets and variables referenced by a project's GitHub
/// Actions workflows.
pub struct ActionsChecklist {
    /// Names referenced via `${{ secrets.X }}`.
    pub secrets: Vec<String>,
    /// Names referenced via `${{ vars.X }}`.
    pub vars: Vec<String>,
}

/// Collect the repository secrets and variables referenced by a project's
/// GitHub Actions workflows.
pub fn collect_actions_checklist(model: &ProjectModel) -> ActionsChecklist {
    let mut secrets: BTreeSet<String> = BTreeSet::new();
    let mut vars: BTreeSet<String> = BTreeSet::new();

    for file in &model.action_files {
        for usage in &file.usages {
            for origin in &usage.origins {
                match origin.subkind.as_deref() {
                    Some("vars") => {
                        vars.insert(usage.name.clone());
                    }
                    Some("secrets") => {
                        secrets.insert(usage.name.clone());
                    }
                    _ => {}
                }
            }
        }
    }

    ActionsChecklist {
        secrets: secrets.into_iter().collect(),
        vars: vars.into_iter().collect(),
    }
}

/// Generate `.github/ENVIRONMENT.md` — a checklist of the repository secrets and
/// variables that must be configured for the workflows to work. Names only;
/// values are never mentioned.
pub fn generate_actions_checklist(model: &ProjectModel) -> String {
    let ActionsChecklist { secrets, vars } = collect_actions_checklist(model);

    let mut lines: Vec<String> = Vec::new();
    lines.push("# GitHub Actions environment checklist".to_string());
    lines.push(String::new());
    lines.push("> Generated by envdoctor. Do not edit by hand.".to_string());
    lines.push(String::new());
    lines.push(
        "Configure these repository secrets and variables (Settings → Secrets and variables → Actions)."
            .to_string(),
    );
    lines.push(String::new());

    lines.push("## Secrets".to_string());
    if secrets.is_empty() {
        lines.push("None.".to_string());
    } else {
        for name in &secrets {
            lines.push(format!("- [ ] `{name}`"));
        }
    }
    lines.push(String::new());

    lines.push("## Variables".to_string());
    if vars.is_empty() {
        lines.push("None.".to_string());
    } else {
        for name in &vars {
            lines.push(format!("- [ ] `{name}`"));
        }
    }
    lines.push(String::new());

    lines.join("\n")
}

/// Generate a GitHub Actions workflow snippet with env vars from the model.
pub fn generate_github_actions(
    model: &crate::models::ProjectModel,
    config: &crate::config::EnvdoctorConfig,
) -> String {
    let mut by_name: HashMap<String, &EnvironmentVariable> = HashMap::new();

    // Prefer env file definitions, then compose, then actions, then k8s
    for file in &model.env_files {
        for v in &file.variables {
            if !config.ignore_variables.is_empty()
                && crate::utils::glob::matches_any_glob(&config.ignore_variables, &v.name)
            {
                continue;
            }
            by_name.entry(v.name.clone()).or_insert(v);
        }
    }
    for file in &model.compose_files {
        for v in &file.variables {
            if !config.ignore_variables.is_empty()
                && crate::utils::glob::matches_any_glob(&config.ignore_variables, &v.name)
            {
                continue;
            }
            by_name.entry(v.name.clone()).or_insert(v);
        }
    }
    for file in &model.action_files {
        for v in &file.variables {
            if !config.ignore_variables.is_empty()
                && crate::utils::glob::matches_any_glob(&config.ignore_variables, &v.name)
            {
                continue;
            }
            by_name.entry(v.name.clone()).or_insert(v);
        }
    }
    for file in &model.k8s_files {
        for v in &file.variables {
            if !config.ignore_variables.is_empty()
                && crate::utils::glob::matches_any_glob(&config.ignore_variables, &v.name)
            {
                continue;
            }
            by_name.entry(v.name.clone()).or_insert(v);
        }
    }

    let mut names: Vec<&String> = by_name.keys().collect();
    names.sort();

    let mut out = String::new();
    out.push_str("# Generated by envdoctor — add to your workflow.\n");
    out.push_str("# Replace ${{ secrets.X }} with your actual secret names.\n\n");

    // Separate secrets from regular vars
    let mut secrets = Vec::new();
    let mut regular = Vec::new();

    for name in &names {
        let v = by_name[*name];
        if v.is_secret {
            secrets.push(*name);
        } else {
            regular.push(*name);
        }
    }

    if regular.is_empty() && secrets.is_empty() {
        return out;
    }

    out.push_str("env:\n");
    for name in &regular {
        let v = by_name[*name];
        let val = v.value.as_deref().unwrap_or("REPLACE_ME");
        // Escape for YAML
        let escaped = val.replace('"', "\\\"");
        out.push_str(&format!("  {}: \"{}\"\n", name, escaped));
    }
    for name in &secrets {
        out.push_str(&format!("  {}: ${{{{ secrets.{} }}}}\n", name, name.to_uppercase()));
    }
    out.push('\n');

    out
}

/// Generate a complete workflow file with all env vars.
pub fn generate_github_actions_workflow(
    model: &crate::models::ProjectModel,
    config: &crate::config::EnvdoctorConfig,
    job_name: &str,
) -> String {
    let env_section = generate_github_actions(model, config);

    format!(r#"# Generated by envdoctor — save as .github/workflows/{}.yml
name: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  {}:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

{}
      - name: Run envdoctor
        run: |
          curl -fsSL https://raw.githubusercontent.com/arun-skg/envdoctor/main/install.sh | bash
          envdoctor scan
"#, job_name.replace(' ', "-").to_lowercase(), job_name, job_name.replace(' ', "-"), env_section)
}