use crate::config::EnvdoctorConfig;
use crate::models::VariableType;

/// Infer a validation schema for every known environment variable by inspecting
/// existing env values and source-code usage patterns, then emit it as a
/// TypeScript module (`envdoctor.schema.ts`). Mirrors the TS `generateSchema`.
///
///   - parseInt(process.env.PORT)     → integer
///   - Number(process.env.RATIO)      → float
///   - process.env.DEBUG === "true"   → boolean
///   - JSON.parse(process.env.CONFIG) → json
///   - process.env.API_URL            → string (dropped; nothing to assert)
pub fn generate_variable_schema_ts(model: &crate::models::ProjectModel) -> String {
    // name → type string (e.g. "integer")
    let mut schema: std::collections::BTreeMap<String, String> = std::collections::BTreeMap::new();

    // Infer from existing env values first.
    for file in &model.env_files {
        for v in &file.variables {
            let Some(value) = &v.value else { continue };
            if let Some(mapped) = map_inferred_type(crate::utils::type_infer::infer_type(Some(value)))
            {
                schema.insert(v.name.clone(), mapped.to_string());
            }
        }
    }

    // Refine from source usage patterns.
    for file in &model.source_files {
        let Ok(content) = std::fs::read_to_string(&file.file_path) else {
            continue;
        };
        let lines: Vec<&str> = content.split('\n').collect();
        for usage in &file.usages {
            for origin in &usage.origins {
                let Some(line_no) = origin.line else { continue };
                let line = lines.get(line_no.saturating_sub(1)).copied().unwrap_or("");
                if let Some(inferred) = infer_from_line(&usage.name, line) {
                    schema.insert(usage.name.clone(), inferred.to_string());
                }
            }
        }
    }

    if schema.is_empty() {
        return "// Generated by envdoctor. No schema could be inferred.\nexport default {\n  schema: {},\n};\n".to_string();
    }

    let mut lines: Vec<String> = Vec::new();
    lines.push("// Generated by envdoctor. Merge into envdoctor.config.ts:".to_string());
    lines.push(
        "// import schema from './envdoctor.schema'; export default { ..., ...schema };".to_string(),
    );
    lines.push(String::new());
    lines.push("export default {".to_string());
    lines.push("  schema: {".to_string());
    for (name, ty) in &schema {
        lines.push(format!("    {name}: {{ type: \"{ty}\" }},"));
    }
    lines.push("  },".to_string());
    lines.push("};".to_string());
    lines.push(String::new());
    lines.join("\n")
}

/// Map an inferred variable type onto a schema type, dropping `string`/`unknown`
/// (nothing worth asserting).
fn map_inferred_type(ty: VariableType) -> Option<&'static str> {
    match ty {
        VariableType::Integer => Some("integer"),
        VariableType::Float => Some("float"),
        VariableType::Boolean => Some("boolean"),
        VariableType::Url => Some("url"),
        VariableType::Json => Some("json"),
        VariableType::String | VariableType::Unknown => None,
    }
}

/// Infer a schema type from a single source line's access pattern.
fn infer_from_line(name: &str, line: &str) -> Option<&'static str> {
    let escaped = regex::escape(name);
    let access = format!(r"process\.env\.{escaped}|import\.meta\.env\.{escaped}");

    let int_re = regex::Regex::new(&format!(r"(parseInt|Number\.parseInt)\s*\(\s*({access})")).unwrap();
    if int_re.is_match(line) {
        return Some("integer");
    }
    let float_re = regex::Regex::new(&format!(
        r"(Number\s*\(\s*({access})\s*\)|parseFloat|Number\.parseFloat)\s*\(\s*({access})"
    ))
    .unwrap();
    if float_re.is_match(line) {
        return Some("float");
    }
    let bool_re = regex::Regex::new(&format!(
        r#"({access})\s*===?\s*["']true["']|({access})\s*===?\s*["']false["']|Boolean\s*\(\s*({access})"#
    ))
    .unwrap();
    if bool_re.is_match(line) {
        return Some("boolean");
    }
    let json_re = regex::Regex::new(&format!(r"JSON\.parse\s*\(\s*({access})")).unwrap();
    if json_re.is_match(line) {
        return Some("json");
    }
    None
}

/// Generate a JSON schema for envdoctor configuration.
pub fn generate_config_schema() -> String {
    serde_json::to_string_pretty(&json_schema()).unwrap()
}

fn json_schema() -> serde_json::Value {
    serde_json::json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "envdoctor configuration",
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "envFilePatterns": {
                "type": "array",
                "items": { "type": "string" },
                "description": "Glob patterns for dotenv files"
            },
            "composeFilePatterns": {
                "type": "array",
                "items": { "type": "string" },
                "description": "Glob patterns for docker-compose files"
            },
            "actionsFilePatterns": {
                "type": "array",
                "items": { "type": "string" },
                "description": "Glob patterns for GitHub Actions workflows"
            },
            "k8sFilePatterns": {
                "type": "array",
                "items": { "type": "string" },
                "description": "Glob patterns for Kubernetes manifests"
            },
            "sourceExtensions": {
                "type": "array",
                "items": { "type": "string" },
                "description": "File extensions to scan for source usage"
            },
            "ignoreVariables": {
                "type": "array",
                "items": { "type": "string" },
                "description": "Glob patterns of variable names to never report"
            },
            "ignoreFiles": {
                "type": "array",
                "items": { "type": "string" },
                "description": "Glob patterns of files to skip"
            },
            "environments": {
                "type": "object",
                "additionalProperties": {
                    "type": "array",
                    "items": { "type": "string" }
                },
                "description": "Environment label -> file glob mapping"
            },
            "strict": {
                "type": "boolean",
                "description": "Fail on warnings"
            },
            "rules": {
                "type": "object",
                "additionalProperties": {
                    "type": "string",
                    "enum": ["error", "warning", "off"]
                },
                "description": "Per-detector severity overrides"
            },
            "schema": {
                "type": "object",
                "additionalProperties": { "$ref": "#/definitions/variableSchema" },
                "description": "Per-variable validation schema"
            }
        },
        "definitions": {
            "variableSchema": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": ["string", "integer", "float", "boolean", "url", "json", "enum", "regex"]
                    },
                    "optional": { "type": "boolean" },
                    "enum": {
                        "type": "array",
                        "items": { "type": "string" }
                    },
                    "regex": { "type": "string" },
                    "min": { "type": "integer" },
                    "max": { "type": "integer" }
                }
            }
        }
    })
}

/// Generate a TOML config template with all options commented.
pub fn generate_config_template() -> String {
    r#"# envdoctor configuration
# All fields are optional; uncomment and adjust as needed.

# envFilePatterns = [".env", ".env.*"]
# composeFilePatterns = ["**/docker-compose*.y*ml", "**/compose*.y*ml"]
# actionsFilePatterns = [".github/workflows/**/*.y*ml"]
# k8sFilePatterns = [
#   "**/*.{deployment,service,statefulset,daemonset,cronjob,job,configmap,secret,ingress,pvc}.y*ml",
#   "**/k8s/**/*.y*ml",
#   "**/kubernetes/**/*.y*ml",
#   "**/manifests/**/*.y*ml",
#   "**/deploy/**/*.y*ml"
# ]
# sourceExtensions = ["ts", "tsx", "js", "jsx", "mjs", "cjs"]
# ignoreVariables = ["AWS_*", "GOOGLE_*"]
# ignoreFiles = ["**/vendor/**", "**/node_modules/**"]
# strict = false

# [environments]
# development = [".env.development", ".env.local"]
# production = [".env.production"]
# staging = [".env.staging"]

# [rules]
# unused = "off"
# "environment-diff" = "warn"

# [schema]
# PORT = { type = "integer", min = 1, max = 65535 }
# NODE_ENV = { type = "enum", enum = ["development", "production", "test"] }
# DATABASE_URL = { type = "url" }
# LOG_LEVEL = { type = "enum", enum = ["debug", "info", "warn", "error"] }
# CONFIG_JSON = { type = "json" }
# ID_PATTERN = { type = "regex", regex = "^[A-Z_]+$" }
"#
    .to_string()
}

/// Generate a schema.json file from the config's variable schemas.
pub fn generate_variable_schema_json(config: &EnvdoctorConfig) -> String {
    if config.schema.is_empty() {
        return "{}".to_string();
    }

    let mut map = serde_json::Map::new();
    for (name, schema) in &config.schema {
        let mut obj = serde_json::Map::new();
        if let Some(t) = &schema.var_type {
            obj.insert("type".to_string(), serde_json::json!(format!("{:?}", t).to_lowercase()));
        }
        if let Some(opt) = schema.optional {
            obj.insert("optional".to_string(), serde_json::json!(opt));
        }
        if let Some(enums) = &schema.enum_values {
            obj.insert("enum".to_string(), serde_json::json!(enums));
        }
        if let Some(regex) = &schema.regex {
            obj.insert("pattern".to_string(), serde_json::json!(regex));
        }
        if let Some(min) = schema.min {
            obj.insert("minimum".to_string(), serde_json::json!(min));
        }
        if let Some(max) = schema.max {
            obj.insert("maximum".to_string(), serde_json::json!(max));
        }
        map.insert(name.clone(), serde_json::Value::Object(obj));
    }

    serde_json::to_string_pretty(&serde_json::Value::Object(map)).unwrap()
}