import Foundation

/// Generate a deterministic `.env.example` for a project.
///
/// Security rules:
/// - Secret-like variables always get a blank value.
/// - Non-secret values are copied ONLY from the base `.env` (development) file.
public enum EnvExampleGenerator {
    public static func generateEnvExample(_ model: ProjectModel) -> String {
        // Names the app actually consumes (source + compose + actions).
        var used = Set<String>()
        for file in model.sourceFiles + model.composeFiles + model.actionFiles {
            for v in file.variables { used.insert(v.name) }
            for v in file.usages { used.insert(v.name) }
        }

        // Names defined in environment files (including .env.example).
        var defined = Set<String>()
        for file in model.envFiles {
            for v in file.variables { defined.insert(v.name) }
        }

        let required = used
        let optional = defined.subtracting(required)

        var lines: [String] = []
        lines.append("# .env.example")
        lines.append("# Generated by envdoctor. Copy to .env and fill in real values.")
        lines.append("# Secret values are intentionally left blank — never commit secrets.")
        lines.append("")

        func valueFor(_ name: String) -> String {
            if isSecretName(name) { return "" }
            let base = model.envFiles.first { file in
                file.environment == "development"
                    && file.variables.contains { $0.name == name && ($0.value ?? "") != "" }
            }
            guard let def = base?.variables.first(where: { $0.name == name }) else { return "" }
            return def.value ?? ""
        }

        if !required.isEmpty {
            lines.append("# Required by the application")
            for name in Locale.sorted(required) {
                lines.append("\(name)=\(valueFor(name))")
            }
            lines.append("")
        }

        if !optional.isEmpty {
            lines.append("# Optional / configuration knobs")
            for name in Locale.sorted(optional) {
                lines.append("\(name)=\(valueFor(name))")
            }
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }
}
