import Foundation

/// Generate `ENVIRONMENT.md` — a human-readable reference for a project's
/// environment variables. Names only; no values ever appear.
public enum EnvironmentDocGenerator {
    private struct NameInfo {
        var type: VariableType?
        var environments: [String]
        var usedInSource: Bool
        var isSecret: Bool
    }

    private struct NamesIndex {
        var sorted: [String]
        var info: [String: NameInfo]
        var missing: [String]
    }

    public static func generateEnvironmentDoc(_ model: ProjectModel) -> String {
        let names = collectNames(model)

        var lines: [String] = []
        lines.append("# Environment Variables")
        lines.append("")
        lines.append("> Generated by envdoctor. Do not edit by hand — run `envdoctor fix` to regenerate.")
        lines.append("")

        // ---- Overview table ----
        lines.append("## Overview")
        lines.append("")
        lines.append("| Variable | Type | Defined in | Used in source | Secret |")
        lines.append("| --- | --- | --- | --- | --- |")
        for name in names.sorted {
            let info = names.info[name] ?? NameInfo(type: nil, environments: [], usedInSource: false, isSecret: false)
            let type = info.type?.label ?? "unknown"
            let envs = info.environments.isEmpty ? "—" : info.environments.joined(separator: ", ")
            let source = info.usedInSource ? "✓" : "—"
            let secret = info.isSecret ? "✓" : "—"
            lines.append("| \(name) | \(type) | \(envs) | \(source) | \(secret) |")
        }
        lines.append("")

        // ---- Missing ----
        if !names.missing.isEmpty {
            lines.append("## Referenced but not defined")
            lines.append("")
            lines.append("These variables are expected somewhere in the project but are not defined in any environment file:")
            lines.append("")
            for name in names.missing {
                lines.append("- `\(name)`")
            }
            lines.append("")
        }

        // ---- Per-environment sections ----
        lines.append("## Environments")
        lines.append("")
        let envLabels = distinctEnvLabels(model)
        if envLabels.isEmpty {
            lines.append("No environment files found.")
            lines.append("")
        } else {
            for label in envLabels {
                let files = model.envFiles
                    .filter { $0.environment == label }
                    .map { "`\($0.filePath)`" }
                lines.append("### \(label)")
                lines.append("")
                lines.append(files.isEmpty ? "" : "Defined in \(files.joined(separator: ", ")).")
                let vars = names.sorted.filter { name in
                    guard let info = names.info[name] else { return false }
                    return info.environments.contains(label)
                }
                for name in vars { lines.append("- \(name)") }
                lines.append("")
            }
        }

        return lines.joined(separator: "\n")
    }

    private static func collectNames(_ model: ProjectModel) -> NamesIndex {
        var names = Set<String>()
        var info: [String: NameInfo] = [:]
        var exampleNames = Set<String>()
        var infoOrder: [String] = []

        func ensure(_ name: String, secret: Bool) {
            if info[name] == nil {
                info[name] = NameInfo(type: nil, environments: [], usedInSource: false, isSecret: secret)
                infoOrder.append(name)
            } else if secret {
                info[name]!.isSecret = true
            }
        }

        // Definitions and usages from environment files. `.env.example` is
        // documentation — it does not count as a real environment.
        for file in model.envFiles {
            for v in file.variables {
                names.insert(v.name)
                if file.environment == "example" {
                    exampleNames.insert(v.name)
                    continue
                }
                ensure(v.name, secret: v.isSecret)
                if let env = file.environment, !info[v.name]!.environments.contains(env) {
                    info[v.name]!.environments.append(env)
                }
                if info[v.name]!.type == nil && v.type != .unknown {
                    info[v.name]!.type = v.type
                }
            }
        }

        // Source usages.
        var sourceUsed = Set<String>()
        for file in model.sourceFiles {
            for v in file.usages {
                names.insert(v.name)
                sourceUsed.insert(v.name)
            }
        }

        // Compose definitions and usages. GitHub Actions is intentionally excluded.
        var composeRefs = Set<String>()
        for file in model.composeFiles {
            for v in file.variables {
                names.insert(v.name)
                composeRefs.insert(v.name)
                ensure(v.name, secret: v.isSecret)
            }
            for v in file.usages {
                names.insert(v.name)
                composeRefs.insert(v.name)
            }
        }

        for name in sourceUsed {
            ensure(name, secret: false)
            info[name]!.usedInSource = true
        }

        // Referenced but not defined in any real environment file.
        let missing = names.filter { name in
            if (info[name]?.environments.count ?? 0) > 0 { return false }
            return sourceUsed.contains(name) || composeRefs.contains(name) || exampleNames.contains(name)
        }

        let sorted = Locale.sorted(names)
        return NamesIndex(sorted: sorted, info: info, missing: missing.sorted())
    }

    private static func distinctEnvLabels(_ model: ProjectModel) -> [String] {
        var labels = Set<String>()
        for file in model.envFiles {
            if let env = file.environment, env != "example" {
                labels.insert(env)
            }
        }
        return labels.sorted()
    }
}
