import Foundation

/// Generate a TypeScript ambient declaration for NodeJS.ProcessEnv based on all
/// known environment variables. Values are never emitted — only names and
/// inferred types as JSDoc comments.
public enum EnvTypesGenerator {
    public static func generateEnvTypes(_ model: ProjectModel) -> String {
        struct Meta {
            var isSecret: Bool
            var inferredType: String?
        }
        var names: [String: Meta] = [:]
        var order: [String] = []

        func ensure(_ name: String, secret: Bool) {
            if names[name] == nil {
                names[name] = Meta(isSecret: secret, inferredType: nil)
                order.append(name)
            }
        }

        for file in model.allFiles {
            for v in file.variables {
                ensure(v.name, secret: v.isSecret)
                if v.type != .unknown, names[v.name]?.inferredType == nil {
                    names[v.name]?.inferredType = v.type.label
                }
            }
            for v in file.usages {
                ensure(v.name, secret: v.isSecret)
            }
        }

        var lines: [String] = []
        lines.append("// Generated by envdoctor. Do not edit manually.")
        lines.append("// This file declares types for process.env variables.")
        lines.append("// Secret values are never included.")
        lines.append("")
        lines.append("declare global {")
        lines.append("  namespace NodeJS {")
        lines.append("    interface ProcessEnv {")

        let sortedNames = Locale.sorted(order)
        for name in sortedNames {
            let meta = names[name]!
            var docParts: [String] = []
            if meta.isSecret { docParts.append("secret") }
            if let inferred = meta.inferredType { docParts.append("inferred type: \(inferred)") }
            if !docParts.isEmpty {
                lines.append("      /** \(docParts.joined(separator: " · ")) */")
            }
            lines.append("      \(name): string;")
        }

        lines.append("    }")
        lines.append("  }")
        lines.append("}")
        lines.append("")
        lines.append("export {};")
        lines.append("")

        return lines.joined(separator: "\n")
    }
}
