import Foundation

public struct ActionsChecklist {
    /// Names referenced via `${{ secrets.X }}`.
    public var secrets: [String]
    /// Names referenced via `${{ vars.X }}`.
    public var vars: [String]
}

public enum GithubActionsGenerator {
    /// Collect the repository secrets and variables referenced by a project's
    /// GitHub Actions workflows.
    public static func collectActionsChecklist(_ model: ProjectModel) -> ActionsChecklist {
        var secrets = Set<String>()
        var vars = Set<String>()

        for file in model.actionFiles {
            for usage in file.usages {
                for origin in usage.origins {
                    if origin.subkind == "vars" {
                        vars.insert(usage.name)
                    } else if origin.subkind == "secrets" {
                        secrets.insert(usage.name)
                    }
                }
            }
        }

        return ActionsChecklist(secrets: Locale.sorted(secrets), vars: Locale.sorted(vars))
    }

    /// Generate `.github/ENVIRONMENT.md` — a checklist of the repository
    /// secrets and variables that must be configured for the workflows to
    /// work. Names only; values are never mentioned.
    public static func generateActionsChecklist(_ model: ProjectModel) -> String {
        let checklist = collectActionsChecklist(model)

        var lines: [String] = []
        lines.append("# GitHub Actions environment checklist")
        lines.append("")
        lines.append("> Generated by envdoctor. Do not edit by hand.")
        lines.append("")
        lines.append("Configure these repository secrets and variables (Settings → Secrets and variables → Actions).")
        lines.append("")

        lines.append("## Secrets")
        if checklist.secrets.isEmpty {
            lines.append("None.")
        } else {
            for name in checklist.secrets {
                lines.append("- [ ] `\(name)`")
            }
        }
        lines.append("")

        lines.append("## Variables")
        if checklist.vars.isEmpty {
            lines.append("None.")
        } else {
            for name in checklist.vars {
                lines.append("- [ ] `\(name)`")
            }
        }
        lines.append("")

        return lines.joined(separator: "\n")
    }

    /// Generate a GitHub Actions workflow snippet with env vars from the model.
    public static func generateGithubActions(_ model: ProjectModel, config: EnvdoctorConfig) -> String {
        var byName: [String: EnvironmentVariable] = [:]

        // Prefer env file definitions, then compose, then actions, then k8s.
        for files in [model.envFiles, model.composeFiles, model.actionFiles, model.k8sFiles] {
            for file in files {
                for v in file.variables {
                    if !config.ignoreVariables.isEmpty && Glob.matchesAnyGlob(config.ignoreVariables, v.name) {
                        continue
                    }
                    if byName[v.name] == nil {
                        byName[v.name] = v
                    }
                }
            }
        }

        let names = Locale.sorted(byName.keys)

        var out = ""
        out += "# Generated by envdoctor — add to your workflow.\n"
        out += "# Replace ${{ secrets.X }} with your actual secret names.\n\n"

        var secrets: [String] = []
        var regular: [String] = []

        for name in names {
            if byName[name]!.isSecret {
                secrets.append(name)
            } else {
                regular.append(name)
            }
        }

        if regular.isEmpty && secrets.isEmpty {
            return out
        }

        out += "env:\n"
        for name in regular {
            let value = byName[name]!.value ?? "REPLACE_ME"
            let escaped = value.replacingOccurrences(of: "\"", with: "\\\"")
            out += "  \(name): \"\(escaped)\"\n"
        }
        for name in secrets {
            out += "  \(name): ${{ secrets.\(name.uppercased()) }}\n"
        }
        out += "\n"

        return out
    }
}
