import Foundation

/// Schema-related generators: the inferred `envdoctor.schema.ts` (used by
/// `fix`), the static `config-schema` JSON, and the `config-template` TOML.
public enum SchemaGenerator {
    /// Infer a validation schema for every known environment variable by
    /// inspecting existing env values and source-code usage patterns, then
    /// emit it as a TypeScript module (`envdoctor.schema.ts`).
    public static func generateVariableSchemaTs(_ model: ProjectModel) -> String {
        // name → type string (e.g. "integer")
        var schema: [String: String] = [:]

        // Infer from existing env values first.
        for file in model.envFiles {
            for v in file.variables {
                guard let value = v.value, mapInferredType(TypeInfer.inferType(value)) != nil else { continue }
                schema[v.name] = mapInferredType(TypeInfer.inferType(value))
            }
        }

        // Refine from source usage patterns.
        for file in model.sourceFiles {
            guard let content = try? String(contentsOfFile: file.filePath, encoding: .utf8) else { continue }
            let lines = content.components(separatedBy: "\n")
            for usage in file.usages {
                for origin in usage.origins {
                    guard let lineNo = origin.line else { continue }
                    guard lineNo - 1 >= 0, lineNo - 1 < lines.count else { continue }
                    let line = lines[lineNo - 1]
                    if let inferred = inferFromLine(usage.name, line) {
                        schema[usage.name] = inferred
                    }
                }
            }
        }

        if schema.isEmpty {
            return "// Generated by envdoctor. No schema could be inferred.\nexport default {\n  schema: {},\n};\n"
        }

        var lines: [String] = []
        lines.append("// Generated by envdoctor. Merge into envdoctor.config.ts:")
        lines.append("// import schema from './envdoctor.schema'; export default { ..., ...schema };")
        lines.append("")
        lines.append("export default {")
        lines.append("  schema: {")
        // Match the TS reference: entries are ordered by `localeCompare`.
        let entries = schema.sorted { Locale.localeCompare($0.key, $1.key) < 0 }
        for (name, type) in entries {
            lines.append("    \(name): { type: \"\(type)\" },")
        }
        lines.append("  },")
        lines.append("};")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private static func mapInferredType(_ type: VariableType) -> String? {
        switch type {
        case .integer: return "integer"
        case .float: return "float"
        case .boolean: return "boolean"
        case .url: return "url"
        case .json: return "json"
        case .string, .unknown: return nil
        }
    }

    private static func inferFromLine(_ name: String, _ line: String) -> String? {
        let escaped = NSRegularExpression.escapedPattern(for: name)
        let access = "process\\.env\\.\(escaped)|import\\.meta\\.env\\.\(escaped)"
        func matches(_ pattern: String) -> Bool {
            guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
            let range = NSRange(line.startIndex..<line.endIndex, in: line)
            return re.firstMatch(in: line, range: range) != nil
        }

        if matches("(parseInt|Number\\.parseInt)\\s*\\(\\s*(\(access))") {
            return "integer"
        }
        if matches("(Number\\s*\\(\\s*(\(access))\\s*\\)|parseFloat|Number\\.parseFloat)\\s*\\(\\s*(\(access))") {
            return "float"
        }
        if matches("(\(access))\\s*===?\\s*[\"']true[\"']|(\(access))\\s*===?\\s*[\"']false[\"']|Boolean\\s*\\(\\s*(\(access))") {
            return "boolean"
        }
        if matches("JSON\\.parse\\s*\\(\\s*(\(access))") {
            return "json"
        }
        return nil
    }

    /// Generate a JSON schema for envdoctor configuration.
    public static func generateConfigSchema() -> String {
        func stringArrayProp(_ description: String) -> JSONValue {
            var items = JSONObject()
            items.set("type", .string("string"))
            var prop = JSONObject()
            prop.set("type", .string("array"))
            prop.set("items", .object(items))
            prop.set("description", .string(description))
            return .object(prop)
        }

        var environmentsAdditional = JSONObject()
        var envItems = JSONObject()
        envItems.set("type", .string("string"))
        environmentsAdditional.set("type", .string("array"))
        environmentsAdditional.set("items", .object(envItems))
        var environments = JSONObject()
        environments.set("type", .string("object"))
        environments.set("additionalProperties", .object(environmentsAdditional))
        environments.set("description", .string("Environment label -> file glob mapping"))

        var strict = JSONObject()
        strict.set("type", .string("boolean"))
        strict.set("description", .string("Fail on warnings"))

        var rulesAdditional = JSONObject()
        rulesAdditional.set("type", .string("string"))
        rulesAdditional.set("enum", .array(["error", "warning", "off"].map { .string($0) }))
        var rules = JSONObject()
        rules.set("type", .string("object"))
        rules.set("additionalProperties", .object(rulesAdditional))
        rules.set("description", .string("Per-detector severity overrides"))

        var schemaAdditional = JSONObject()
        schemaAdditional.set("$ref", .string("#/definitions/variableSchema"))
        var schemaProp = JSONObject()
        schemaProp.set("type", .string("object"))
        schemaProp.set("additionalProperties", .object(schemaAdditional))
        schemaProp.set("description", .string("Per-variable validation schema"))

        var properties = JSONObject()
        properties.set("envFilePatterns", stringArrayProp("Glob patterns for dotenv files"))
        properties.set("composeFilePatterns", stringArrayProp("Glob patterns for docker-compose files"))
        properties.set("actionsFilePatterns", stringArrayProp("Glob patterns for GitHub Actions workflows"))
        properties.set("k8sFilePatterns", stringArrayProp("Glob patterns for Kubernetes manifests"))
        properties.set("sourceExtensions", stringArrayProp("File extensions to scan for source usage"))
        properties.set("ignoreVariables", stringArrayProp("Glob patterns of variable names to never report"))
        properties.set("ignoreFiles", stringArrayProp("Glob patterns of files to skip"))
        properties.set("environments", .object(environments))
        properties.set("strict", .object(strict))
        properties.set("rules", .object(rules))
        properties.set("schema", .object(schemaProp))

        var typeEnum = JSONObject()
        typeEnum.set("type", .string("string"))
        typeEnum.set("enum", .array(["string", "integer", "float", "boolean", "url", "json", "enum", "regex"].map { .string($0) }))
        var optional = JSONObject()
        optional.set("type", .string("boolean"))
        var enumItems = JSONObject()
        enumItems.set("type", .string("string"))
        var `enum` = JSONObject()
        `enum`.set("type", .string("array"))
        `enum`.set("items", .object(enumItems))
        var regex = JSONObject()
        regex.set("type", .string("string"))
        var min = JSONObject()
        min.set("type", .string("integer"))
        var max = JSONObject()
        max.set("type", .string("integer"))

        var variableProperties = JSONObject()
        variableProperties.set("type", .object(typeEnum))
        variableProperties.set("optional", .object(optional))
        variableProperties.set("enum", .object(`enum`))
        variableProperties.set("regex", .object(regex))
        variableProperties.set("min", .object(min))
        variableProperties.set("max", .object(max))

        var variableSchema = JSONObject()
        variableSchema.set("type", .string("object"))
        variableSchema.set("additionalProperties", .bool(false))
        variableSchema.set("properties", .object(variableProperties))

        var definitions = JSONObject()
        definitions.set("variableSchema", .object(variableSchema))

        var root = JSONObject()
        root.set("$schema", .string("http://json-schema.org/draft-07/schema#"))
        root.set("title", .string("envdoctor configuration"))
        root.set("type", .string("object"))
        root.set("additionalProperties", .bool(false))
        root.set("properties", .object(properties))
        root.set("definitions", .object(definitions))

        return Json.pretty(.object(root))
    }

    /// Generate a TOML config template with all options commented.
    public static func generateConfigTemplate() -> String {
        """
        # envdoctor configuration
        # All fields are optional; uncomment and adjust as needed.

        # envFilePatterns = [".env", ".env.*"]
        # composeFilePatterns = ["**/docker-compose*.y*ml", "**/compose*.y*ml"]
        # actionsFilePatterns = [".github/workflows/**/*.y*ml"]
        # k8sFilePatterns = [
        #   "**/*.{deployment,service,statefulset,daemonset,cronjob,job,configmap,secret,ingress,pvc}.y*ml",
        #   "**/k8s/**/*.y*ml",
        #   "**/kubernetes/**/*.y*ml",
        #   "**/manifests/**/*.y*ml",
        #   "**/deploy/**/*.y*ml"
        # ]
        # sourceExtensions = ["ts", "tsx", "js", "jsx", "mjs", "cjs"]
        # ignoreVariables = ["AWS_*", "GOOGLE_*"]
        # ignoreFiles = ["**/vendor/**", "**/node_modules/**"]
        # strict = false

        # [environments]
        # development = [".env.development", ".env.local"]
        # production = [".env.production"]
        # staging = [".env.staging"]

        # [rules]
        # unused = "off"
        # "environment-diff" = "warn"

        # [schema]
        # PORT = { type = "integer", min = 1, max = 65535 }
        # NODE_ENV = { type = "enum", enum = ["development", "production", "test"] }
        # DATABASE_URL = { type = "url" }
        # LOG_LEVEL = { type = "enum", enum = ["debug", "info", "warn", "error"] }
        # CONFIG_JSON = { type = "json" }
        # ID_PATTERN = { type = "regex", regex = "^[A-Z_]+$" }

        """
    }
}
